<?php

/* PATH */
define('FILE_SURAT_PATH', 'public/files/surat/');
define('UPLOAD_FILE_SURAT_PATH', 'public/files/surat/upload/');
define('FILE_SURAT_DISPOSISI_PATH', 'public/files/surat_disposisi/');
define('UPLOAD_FILE_SURAT_DISPOSISI_PATH', 'public/files/surat_disposisi/upload/');
define('FOTO_PROFIL_PATH', 'public/files/foto_profil/');
define('ETTD_PATH', 'public/files/e_ttd/');
define('FOTO_KK_PATH', 'public/files/foto_kk/');
define('UPLOAD_FOTO_KK_PATH', 'public/files/foto_kk/upload/');

/* EKSTENSI FOTO PROFIL */
define('EKSTENSI_FOTO_PROFIL', ['png', 'jpeg']);

/* MAKSIMAL BUAT NOMOR SURAT BACKDATE */
define('MAKSIMAL_BUAT_NOMOR_SURAT_BACKDATE', 5);

/* USIA PENSIUN */
define('USIA_PENSIUN', 58);

/* BATAS NOMINAL INVOICE */
define('BATAS_NOMINAL_INVOICE', 200000000);

/* ID KANTOR */
define('ID_KANTOR_PUSAT', 1);
/* ID JABATAN KANTOR */
define('ID_JK_DIRUT', 1);
define('ID_JK_SEKPER', 2);
define('ID_JK_SENIOR_MNG_KEUANGAN', 3);
define('ID_JK_DIRKEUM', 4);
define('ID_JK_DIRTEKOP', 5);
define('ID_JABATAN_GM', 29);
define('ID_JABATAN_MANAGER_KEUANGAN', 19);
define('ID_JABATAN_MANAGER_AKUNTANSI', 21);
define('ID_JABATAN_ASISTEN_MANAGER_KEUANGAN', 85);
define('NAMA_JKU_MENGGUNAKAN_NAMA_UNIT', [ID_JABATAN_GM]);

/* ID JABATAN KANTOR USER */
define('ID_JKU_DIRUT', 94);

/* ID GRUP MODUL */
define('GRUP_ADMIN_IT', 1);
define('GRUP_USER', 2);
define('GRUP_ADMIN_HRD', 3);

/* LEVEL JABATAN */
define('LEVEL_DIRUT', 1);
define('LEVEL_SEKPER_DIR', 2);
define('LEVEL_SENIOR_EXPERT', 3);
define('LEVEL_MANAGER', 4);
define('LEVEL_ASMAN', 5);
define('LEVEL_SPV', 6);
define('LEVEL_STAF', 7);

/* BAHASA */
define('BAHASA_INDONESIA', 1);
define('BAHASA_INGGRIS', 2);

/* NEGARA */
define('INDONESIA', 105);

/* RESPONSE CODE */
define('SUKSES', 200);
define('GAGAL', 400);
define('BELUM_MEMILIKI_HAK_AKSES', 401);
define('DATA_TIDAK_DITEMUKAN', 404);

/* STATUS SURAT */
define('DRAF', 1);
define('PROSES', 2);
define('TERBIT', 3);
define('BATAL', 4);

/* SIFAT SURAT */
define('BIASA', 1);
define('SEGERA', 2);
define('BIASA_RAHASIA', 3);
define('SEGERA_RAHASIA', 4);

/* JENIS SURAT */
define('JENIS_SURAT_NOTA_DINAS', 1);
define('JENIS_SURAT_NOTA_DINAS_USULAN_PENGADAAN', 2);
define('JENIS_SURAT_SURAT_KELUAR', 3);
define('JENIS_SURAT_INTERNAL_MEMO', 4);
define('JENIS_SURAT_DELEGASI', 5);
define('JENIS_SURAT_SURAT_EKSTERNAL', 6);

/* STATUS DELEGASI */
define('STATUS_DELEGASI_BELUM_DISETUJUI', 1);
define('STATUS_DELEGASI_MENUNGGU', 2);
define('STATUS_DELEGASI_AKTIF', 3);
define('STATUS_DELEGASI_SELESAI', 4);

/* STATUS BACKDATE */
define('STATUS_BACKDATE_MENUNGGU', 1);
define('STATUS_BACKDATE_AKTIF', 2);
define('STATUS_BACKDATE_SELESAI', 3);

/* STATUS AKSES SURAT TERBIT */
define('STATUS_AKSES_SURAT_TERBIT_AKTIF', 1);
define('STATUS_AKSES_SURAT_TERBIT_TIDAK_AKTIF', 2);

/* JENIS JKU */
define('JENIS_JKU_ASLI', 1);
define('JENIS_JKU_DELEGASI', 2);

/* STATUS PERSETUJUAN SURAT */
define('STATUS_PERSETUJUAN_DISETUJUI', 1);
define('STATUS_PERSETUJUAN_DIKEMBALIKAN', 2);
define('STATUS_PERSETUJUAN_BATAL', 3);

/* STATUS PENOMORAN SURAT */
define('STATUS_PENOMORAN_KOSONG', 1);
define('STATUS_PENOMORAN_DIPESAN', 2);
define('STATUS_PENOMORAN_TERBIT', 3);

/* STATUS SPSM */
define('STATUS_SPSM_DRAF', 1);
define('STATUS_SPSM_DISPOSISI_BELUM_SELESAI', 2);
define('STATUS_SPSM_SELESAI', 3);

/* TIPE AKTIVASI SEKRETARIS */
define('TIPE_AKTIVASI_SEKRETARIS_SEMUA', 1);
define('TIPE_AKTIVASI_SEKRETARIS_PENERBITAN', 2);
define('TIPE_AKTIVASI_SEKRETARIS_PENERIMA', 3);
// define('TIPE_AKTIVASI_SEKRETARIS_DISPOSISI', 4);

/* ARRAY TIPE AKTIVASI SEKRETARIS */
define('AKTIVASI_SEKRETARIS_PENERBITAN', [TIPE_AKTIVASI_SEKRETARIS_SEMUA, TIPE_AKTIVASI_SEKRETARIS_PENERBITAN]);
define('AKTIVASI_SEKRETARIS_PENERIMA', [TIPE_AKTIVASI_SEKRETARIS_SEMUA, TIPE_AKTIVASI_SEKRETARIS_PENERIMA]);
// define('AKTIVASI_SEKRETARIS_DISPOSISI', [TIPE_AKTIVASI_SEKRETARIS_SEMUA, TIPE_AKTIVASI_SEKRETARIS_DISPOSISI]);
// define('AKTIVASI_SEKRETARIS_SURAT_MASUK', [TIPE_AKTIVASI_SEKRETARIS_SEMUA, TIPE_AKTIVASI_SEKRETARIS_PENERIMA, TIPE_AKTIVASI_SEKRETARIS_DISPOSISI]);

/* AKSI SURAT */
define('AKSI_SURAT_KIRIM', 1);
define('AKSI_SURAT_TERBIT', 2);
define('AKSI_SURAT_SETUJU', 3);
define('AKSI_SURAT_KEMBALI', 4);
define('AKSI_SURAT_BATAL', 5);
define('AKSI_SURAT_REVISI', 6);

define('KODE_JABATAN_PAKAI_NAMA_UNIT', ['GM']);
define('SIFAT_SURAT_RAHASIA', [BIASA_RAHASIA, SEGERA_RAHASIA]);
define('JENIS_SURAT_PERSETUJUAN', [JENIS_SURAT_NOTA_DINAS, JENIS_SURAT_NOTA_DINAS_USULAN_PENGADAAN, JENIS_SURAT_SURAT_KELUAR, JENIS_SURAT_INTERNAL_MEMO, JENIS_SURAT_DELEGASI]);
define('JENIS_SURAT_INTERNAL_EKSTERNAL', [JENIS_SURAT_NOTA_DINAS, JENIS_SURAT_NOTA_DINAS_USULAN_PENGADAAN, JENIS_SURAT_SURAT_KELUAR, JENIS_SURAT_INTERNAL_MEMO, JENIS_SURAT_DELEGASI, JENIS_SURAT_SURAT_EKSTERNAL]);

/* JENIS SURAT MASUK */
define('JENIS_SURAT_MASUK_SURAT', 1);
define('JENIS_SURAT_MASUK_TEMBUSAN_SURAT', 2);
define('JENIS_SURAT_MASUK_SURAT_FORWARD', 3);
define('JENIS_SURAT_MASUK_SURAT_DISPOSISI', 4);

/* AKSI DISPOSISI SURAT */
define('AKSI_DISPOSISI_SURAT_DISPOSISI', 1);
define('AKSI_DISPOSISI_SURAT_SELESAI', 2);

/* AKSES JENIS SURAT MASUK */
define('SURAT_MASUK_FORWARD', [JENIS_SURAT_MASUK_SURAT, JENIS_SURAT_MASUK_TEMBUSAN_SURAT, JENIS_SURAT_MASUK_SURAT_FORWARD]);
define('SURAT_MASUK_DISPOSISI', [JENIS_SURAT_MASUK_SURAT, JENIS_SURAT_MASUK_SURAT_DISPOSISI]);

/* JENIS PEMBERKASAN */
define('JENIS_PEMBERKASAN_PLN', 1);

/* JENIS SPSM */
define('JENIS_SPSM_SURAT_MASUK', 1);
define('JENIS_SPSM_SURAT_KELUAR', 2);

/* NAMA AKSI SURAT */
// define('AKSI_SURAT', [
//     AKSI_SURAT_KIRIM => 'Pengiriman',
//     AKSI_SURAT_TERBIT => 'Penerbitan',
//     AKSI_SURAT_SETUJU => 'Penyetujuan',
//     AKSI_SURAT_KEMBALI => 'Pengembalian',
//     AKSI_SURAT_BATAL => 'Pembatalan'
// ]);

/* PENERIMA SURAT EKSTERNAL INVOICE */
//define('ID_JK_MANAGER_KEUANGAN', 19);
define('ID_JK_ASISTEN_MANAGER_KEUANGAN', 110);
define('ID_JK_MANAGER_AKUNTANSI', 21);
define('PENERIMA_SURAT_EKSTERNAL_INVOICE', [ID_JK_ASISTEN_MANAGER_KEUANGAN, ID_JK_MANAGER_AKUNTANSI]);
//define('PENERIMA_SURAT_EKSTERNAL_INVOICE', [ID_JK_MANAGER_KEUANGAN, ID_JK_MANAGER_AKUNTANSI]);

/* MODEL PEMBERKASAN SURAT */
define('MODEL_PEMBERKASAN_SURAT', [
    ['qrcode' => false, 'header_footer' => false, 'nama' => ' Versi 1'],
    ['qrcode' => false, 'header_footer' => true, 'nama' => ' Versi 2'],
    ['qrcode' => true, 'header_footer' => false, 'nama' => ' Versi 3'],
    ['qrcode' => true, 'header_footer' => true, 'nama' => ' Versi 4']
]);

/* BULAN ROMAWI */
define('BULAN_ROMAWI', [
    1 => 'I',
    2 => 'II',
    3 => 'III',
    4 => 'IV',
    5 => 'V',
    6 => 'VI',
    7 => 'VII',
    8 => 'VIII',
    9 => 'IX',
    10 => 'X',
    11 => 'XI',
    12 => 'XII'
]);

/* NAMA BULAN */
define('NAMA_BULAN', [
    1 => 'Januari',
    2 => 'Februari',
    3 => 'Maret',
    4 => 'April',
    5 => 'Mei',
    6 => 'Juni',
    7 => 'Juli',
    8 => 'Agustus',
    9 => 'September',
    10 => 'Oktober',
    11 => 'November',
    12 => 'Desember'
]);

define('FILE_LEMBUR_PATH', 'public/files/lembur/');

/* AKSI LEMBUR */
define('AKSI_LEMBUR_KIRIM', 1);
define('AKSI_LEMBUR_SETUJU', 2);
define('AKSI_LEMBUR_TOLAK', 3);

/* STATUS LEMBUR */
define('STATUS_LEMBUR_DRAF', 1);
define('STATUS_LEMBUR_PROSES', 2);
define('STATUS_LEMBUR_DISETUJUI', 3);
define('STATUS_LEMBUR_DITOLAK', 4);
define('STATUS_LEMBUR_BATAL', 5);

/* STATUS PERSETUJUAN LEMBUR */
define('STATUS_PERSETUJUAN_LEMBUR_DISETUJUI', 1);
define('STATUS_PERSETUJUAN_LEMBUR_DITOLAK', 2);

/* MAKSIMAL PENGAJUAN LEMBUR */
define('BATAS_MAKSIMAL_PENGAJUAN_LEMBUR', 3);

define('FILE_CUTI_PATH', 'public/files/cuti/');
define('UPLOAD_FILE_CUTI_PATH', 'public/files/cuti/upload/');

/* BATAS MINIMAL PENGAJUAN CUTI */
define('BATAS_MINIMAL_PENGAJUAN_CUTI', -90);
define('BATAS_MAKSIMAL_PENGAJUAN_CUTI', 30);

/* BATAS MINIMAL PENGABDIAN UNTUK PENAMBAHAN KUOTA CUTI HARIAN */
define('BATAS_MINIMAL_PENGABDIAN_UNTUK_PENAMBAHAN_KUOTA_CUTI_HARIAN', 10);
/* MINIMAL KUOTA CUTI HARIAN */
define('MINIMAL_KUOTA_CUTI_HARIAN', 12);
/* MAKSIMAL KUOTA CUTI HARIAN */
define('MAKSIMAL_KUOTA_CUTI_HARIAN', 15);
/* MINIMAL MASA KERJA CUTI TIDAK DIBAYAR */
define('MINIMAL_MASA_KERJA_CUTI_TIDAK_DIBAYAR', 3);

/* JENIS HARI LIBUR */
define('JENIS_HARI_LIBUR_BERUBAH_SETIAP_TAHUN', 1);
define('JENIS_HARI_LIBUR_TETAP_SETIAP_TAHUN', 2);
define('JENIS_HARI_LIBUR_CUTI_BERSAMA', 3);

/* JENIS HARI CUTI */
define('JENIS_HARI_CUTI_HARI_KERJA', 1);
define('JENIS_HARI_CUTI_HARI_KALENDER', 2);

/* AKSI CUTI */
define('AKSI_CUTI_KIRIM', 1);
define('AKSI_CUTI_SETUJU', 2);
define('AKSI_CUTI_TOLAK', 3);

/* STATUS CUTI */
define('STATUS_CUTI_DRAF', 1);
define('STATUS_CUTI_PROSES', 2);
define('STATUS_CUTI_DISETUJUI', 3);
define('STATUS_CUTI_DITOLAK', 4);
define('STATUS_CUTI_BATAL', 5);

/* STATUS PERSETUJUAN CUTI */
define('STATUS_PERSETUJUAN_CUTI_DISETUJUI', 1);
define('STATUS_PERSETUJUAN_CUTI_DITOLAK', 2);

/* JENIS CUTI */
define('JENIS_CUTI_HARIAN', 1);
define('JENIS_CUTI_KHUSUS', 2);
define('JENIS_CUTI_HAJI', 3);
define('JENIS_CUTI_IBADAH_KEAGAMAAN', 4);
define('JENIS_CUTI_MELAHIRKAN', 5);
define('JENIS_CUTI_KEGUGURAN', 6);
define('JENIS_CUTI_PERNIKAHAN', 7);
define('JENIS_CUTI_ISTRI_MELAHIRKAN_KEGUGURAN', 8);
define('JENIS_CUTI_KEMATIAN_SUAMI_ISTRI_ANAK', 9);
define('JENIS_CUTI_KEMATIAN_SAUDARA_ORANGTUA_MERTUA', 10);
define('JENIS_CUTI_KEMATIAN_SAUDARA_SUAMI_ISTRI', 11);
define('JENIS_CUTI_KEMATIAN_ANGGOTA_KELUARGA_SATU_RUMAH', 12);
define('JENIS_CUTI_PERNIKAHAN_ANAK', 13);
define('JENIS_CUTI_KHITAN_BAPTIS_ANAK', 14);
define('JENIS_CUTI_SAKIT_KERAS_SUAMI_ISTRI_ANAK_ORANGTUA_MERTUA_MENANTU', 15);
define('JENIS_CUTI_RUMAH_RUSAK_BENCANA_ALAM', 16);
define('JENIS_CUTI_WALI_NIKAH_SAUDARA_KANDUNG', 17);
define('JENIS_CUTI_PANGGILAN_PIHAK_BERWAJIB', 18);
define('JENIS_CUTI_TIDAK_DIBAYAR', 19);

/* GRUP CUTI */
define('CUTI_PENGAJUAN_SAAT_HARI_H', [
    JENIS_CUTI_ISTRI_MELAHIRKAN_KEGUGURAN,
    JENIS_CUTI_KEMATIAN_SUAMI_ISTRI_ANAK,
    JENIS_CUTI_KEMATIAN_SAUDARA_ORANGTUA_MERTUA,
    JENIS_CUTI_KEMATIAN_SAUDARA_SUAMI_ISTRI,
    JENIS_CUTI_KEMATIAN_ANGGOTA_KELUARGA_SATU_RUMAH,
    JENIS_CUTI_SAKIT_KERAS_SUAMI_ISTRI_ANAK_ORANGTUA_MERTUA_MENANTU,
    JENIS_CUTI_RUMAH_RUSAK_BENCANA_ALAM
]);
define('CUTI_PENGAJUAN_SEBELUM_HARI_H', [
    JENIS_CUTI_PERNIKAHAN,
    JENIS_CUTI_PERNIKAHAN_ANAK,
    JENIS_CUTI_KHITAN_BAPTIS_ANAK,
    JENIS_CUTI_WALI_NIKAH_SAUDARA_KANDUNG
]);
define('CUTI_TANPA_TANGGAL_KEJADIAN', [
    JENIS_CUTI_HARIAN,
    JENIS_CUTI_TIDAK_DIBAYAR,
    JENIS_CUTI_HAJI,
    JENIS_CUTI_IBADAH_KEAGAMAAN,
    JENIS_CUTI_PANGGILAN_PIHAK_BERWAJIB
]);
define('CUTI_MELAHIRKAN_KEGUGURAN', [
    JENIS_CUTI_MELAHIRKAN,
    JENIS_CUTI_KEGUGURAN
]);

/* JENIS KELAMIN */
define('LAKI_LAKI', 1);
define('PEREMPUAN', 2);

/* AGAMA */
define('ISLAM', 1);
define('KRISTEN PROTESTAN', 2);
define('KRISTEN_KATOLIK', 3);
define('HINDU', 4);
define('BUDDHA', 5);
define('KONGHUCU', 6);

/* STATUS TANGGUNGAN */
define('STATUS_TANGGUNGAN_TK', 1);
define('STATUS_TANGGUNGAN_TK1', 2);
define('STATUS_TANGGUNGAN_TK2', 3);
define('STATUS_TANGGUNGAN_TK3', 4);
define('STATUS_TANGGUNGAN_K', 5);
define('STATUS_TANGGUNGAN_K1', 6);
define('STATUS_TANGGUNGAN_K2', 7);
define('STATUS_TANGGUNGAN_K3', 8);

/* STATUS TANGGUNGAN TIDAK KAWIN */
define('STATUS_TANGGUNGAN_TIDAK_KAWIN', [STATUS_TANGGUNGAN_TK, STATUS_TANGGUNGAN_TK1, STATUS_TANGGUNGAN_TK2, STATUS_TANGGUNGAN_TK3]);
/* STATUS TANGGUNGAN KAWIN */
define('STATUS_TANGGUNGAN_KAWIN', [STATUS_TANGGUNGAN_K, STATUS_TANGGUNGAN_K1, STATUS_TANGGUNGAN_K2, STATUS_TANGGUNGAN_K3]);
/* STATUS TANGGUNGAN BERANAK */
define('STATUS_TANGGUNGAN_BERANAK', [STATUS_TANGGUNGAN_TK1, STATUS_TANGGUNGAN_TK2, STATUS_TANGGUNGAN_TK3, STATUS_TANGGUNGAN_K1, STATUS_TANGGUNGAN_K2, STATUS_TANGGUNGAN_K3]);

define('FILE_REIMBURSE_PATH', 'public/files/reimburse/');
define('UPLOAD_FILE_REIMBURSE_PATH', 'public/files/reimburse/upload/');

/* MAKSIMAL PENGAJUAN REIMBURSE */
define('BATAS_MAKSIMAL_PENGAJUAN_REIMBURSE', 60);

/* UMUR MAKSIMAL TANGGUNGAN ANAK */
define('UMUR_MAKSIMAL_TANGGUNGAN_ANAK', 23);

/* STATUS HUBUNGAN TANGGUNGAN */
define('STATUS_HUBUNGAN_TANGGUNGAN_KARYAWAN', 1);
define('STATUS_HUBUNGAN_TANGGUNGAN_PASANGAN', 2);
define('STATUS_HUBUNGAN_TANGGUNGAN_ANAK', 3);

/* STATUS PERNIKAHAN */
define('STATUS_PERNIKAH_BELUM_MENIKAH', 1);
define('STATUS_PERNIKAH_MENIKAH', 2);
define('STATUS_PERNIKAH_DUDA_JANDA', 3);

/* AKSI REIMBURSE */
define('AKSI_REIMBURSE_KIRIM', 1);
define('AKSI_REIMBURSE_SETUJU', 2);
define('AKSI_REIMBURSE_TOLAK', 3);
define('AKSI_REIMBURSE_DIAJUKAN', 4);
define('AKSI_REIMBURSE_DIBAYARKAN', 5);

/* STATUS REIMBURSE */
define('STATUS_REIMBURSE_DRAF', 1);
define('STATUS_REIMBURSE_PROSES', 2);
define('STATUS_REIMBURSE_DISETUJUI', 3);
define('STATUS_REIMBURSE_DITOLAK', 4);
define('STATUS_REIMBURSE_DIAJUKAN', 5);
define('STATUS_REIMBURSE_DIBAYARKAN', 6);

/* STATUS PERSETUJUAN REIMBURSE */
define('STATUS_PERSETUJUAN_REIMBURSE_DISETUJUI', 1);
define('STATUS_PERSETUJUAN_REIMBURSE_DITOLAK', 2);

define('FILE_LPD_PATH', 'public/files/lpd/');
define('UPLOAD_FILE_LPD_PATH', 'public/files/lpd/upload/');

/* AKSI LPD */
define('AKSI_LPD_KIRIM', 1);
define('AKSI_LPD_SETUJU', 2);
define('AKSI_LPD_KEMBALI', 3);
define('AKSI_LPD_TOLAK', 4);
define('AKSI_LPD_REVISI', 5);
define('AKSI_LPD_DIAJUKAN', 6);
define('AKSI_LPD_DIBAYARKAN', 7);

/* STATUS LPD */
define('STATUS_LPD_DRAF', 1);
define('STATUS_LPD_PROSES', 2);
define('STATUS_LPD_DISETUJUI', 3);
define('STATUS_LPD_DITOLAK', 4);
define('STATUS_LPD_DIAJUKAN', 5);
define('STATUS_LPD_DIBAYARKAN', 6);

/* STATUS HRD LPD */
define('STATUS_LPD_HRD', [STATUS_LPD_DISETUJUI, STATUS_LPD_DIAJUKAN, STATUS_LPD_DIBAYARKAN]);

/* STATUS PERSETUJUAN LPD */
define('STATUS_PERSETUJUAN_LPD_DISETUJUI', 1);
define('STATUS_PERSETUJUAN_LPD_DIKEMBALIKAN', 2);
define('STATUS_PERSETUJUAN_LPD_DITOLAK', 3);

/* KATEGORI TUJUAN LPD */
define('KATEGORI_TUJUAN_DALAM_NEGERI', 1);
define('KATEGORI_TUJUAN_LUAR_NEGERI_1', 2);
define('KATEGORI_TUJUAN_LUAR_NEGERI_2', 3);

/* KATEGORI TRANSPORTASI LPD */
define('KATEGORI_TRANSPORTASI_UMUM', 1);
define('KATEGORI_TRANSPORTASI_OPERASIONAL', 2);
define('KATEGORI_TRANSPORTASI_PRIBADI', 3);

/* KELAS TRANSPORTASI LPD */
define('KELAS_TRANSPORTASI_EKONOMI', 1);
define('KELAS_TRANSPORTASI_BISNIS', 2);
define('KELAS_TRANSPORTASI_EKSEKUTIF', 3);

/* KATEGORI PEMBAYARAN LPD */
define('KATEGORI_PEMBAYARAN_DIBAYAR_KANTOR', 1);
define('KATEGORI_PEMBAYARAN_DIBAYAR_SENDIRI', 2);

/* JENIS TRANSPORTASI LPD */
define('JENIS_TRANSPORTASI_BUS', 1);
define('JENIS_TRANSPORTASI_PESAWAT', 2);
define('JENIS_TRANSPORTASI_KERETA_API', 3);
define('JENIS_TRANSPORTASI_KAPAL', 4);
define('JENIS_TRANSPORTASI_LAIN_LAIN', 5);

/* STATUS PENGAJUAN TANGGUNGAN */
define('STATUS_PENGAJUAN_TANGGUNGAN_PROSES_PENGAJUAN', 1);
define('STATUS_PENGAJUAN_TANGGUNGAN_DITOLAK', 2);
define('STATUS_PENGAJUAN_TANGGUNGAN_AKTIF', 3);
define('STATUS_PENGAJUAN_TANGGUNGAN_TIDAK_AKTIF', 4);

/* STATUS PERSETUJUAN TANGGUNGAN */
define('STATUS_PERSETUJUAN_TANGGUNGAN_DITERIMA', 1);
define('STATUS_PERSETUJUAN_TANGGUNGAN_DITOLAK', 2);
