<?php
namespace Database\Seeders\ECuti;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class SeederTabelPejabatPemeriksaCuti extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::connection('ecuti_sys')->statement("TRUNCATE TABLE ONLY sys.pejabat_pemeriksa_cuti RESTART IDENTITY CASCADE");
        DB::connection('ecuti_sys')->table('pejabat_pemeriksa_cuti')->insert([
            [ 'id_juu' => 3, 'id_juu_pemeriksa' => 2, 'urutan' => 1 ],
            [ 'id_juu' => 3, 'id_juu_pemeriksa' => 1, 'urutan' => 2 ],
            [ 'id_juu' => 21, 'id_juu_pemeriksa' => 2, 'urutan' => 1 ],
            [ 'id_juu' => 21, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 23, 'id_juu_pemeriksa' => 2, 'urutan' => 1 ],
            [ 'id_juu' => 23, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 14, 'id_juu_pemeriksa' => 2, 'urutan' => 1 ],
            [ 'id_juu' => 14, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 7, 'id_juu_pemeriksa' => 21, 'urutan' => 1 ],
            [ 'id_juu' => 7, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 16, 'id_juu_pemeriksa' => 21, 'urutan' => 1 ],
            [ 'id_juu' => 16, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 20, 'id_juu_pemeriksa' => 21, 'urutan' => 1 ],
            [ 'id_juu' => 20, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 27, 'id_juu_pemeriksa' => 21, 'urutan' => 1 ],
            [ 'id_juu' => 27, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 12, 'id_juu_pemeriksa' => 21, 'urutan' => 1 ],
            [ 'id_juu' => 12, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 22, 'id_juu_pemeriksa' => 21, 'urutan' => 1 ],
            [ 'id_juu' => 22, 'id_juu_pemeriksa' => 2, 'urutan' => 2 ],
            [ 'id_juu' => 17, 'id_juu_pemeriksa' => 23, 'urutan' => 1 ],
            [ 'id_juu' => 17, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 25, 'id_juu_pemeriksa' => 23, 'urutan' => 1 ],
            [ 'id_juu' => 25, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 26, 'id_juu_pemeriksa' => 23, 'urutan' => 1 ],
            [ 'id_juu' => 26, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 11, 'id_juu_pemeriksa' => 23, 'urutan' => 1 ],
            [ 'id_juu' => 11, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 8, 'id_juu_pemeriksa' => 2, 'urutan' => 1 ],
            [ 'id_juu' => 8, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 28, 'id_juu_pemeriksa' => 8, 'urutan' => 1 ],
            [ 'id_juu' => 28, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 15, 'id_juu_pemeriksa' => 8, 'urutan' => 1 ],
            [ 'id_juu' => 15, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 9, 'id_juu_pemeriksa' => 2, 'urutan' => 1 ],
            [ 'id_juu' => 9, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 29, 'id_juu_pemeriksa' => 9, 'urutan' => 1 ],
            [ 'id_juu' => 29, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 71, 'id_juu_pemeriksa' => 73, 'urutan' => 1 ],
            [ 'id_juu' => 71, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 5, 'id_juu_pemeriksa' => 1, 'urutan' => 1 ],
            [ 'id_juu' => 5, 'id_juu_pemeriksa' => 1, 'urutan' => 2 ],
            [ 'id_juu' => 13, 'id_juu_pemeriksa' => 5, 'urutan' => 1 ],
            [ 'id_juu' => 13, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 38, 'id_juu_pemeriksa' => 5, 'urutan' => 1 ],
            [ 'id_juu' => 38, 'id_juu_pemeriksa' => 1, 'urutan' => 2 ],
            [ 'id_juu' => 36, 'id_juu_pemeriksa' => 38, 'urutan' => 1 ],
            [ 'id_juu' => 36, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 30, 'id_juu_pemeriksa' => 38, 'urutan' => 1 ],
            [ 'id_juu' => 30, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 50, 'id_juu_pemeriksa' => 57, 'urutan' => 1 ],
            [ 'id_juu' => 50, 'id_juu_pemeriksa' => 51, 'urutan' => 2 ],
            [ 'id_juu' => 52, 'id_juu_pemeriksa' => 55, 'urutan' => 1 ],
            [ 'id_juu' => 52, 'id_juu_pemeriksa' => 51, 'urutan' => 2 ],
            [ 'id_juu' => 34, 'id_juu_pemeriksa' => 36, 'urutan' => 1 ],
            [ 'id_juu' => 34, 'id_juu_pemeriksa' => 38, 'urutan' => 2 ],
            [ 'id_juu' => 37, 'id_juu_pemeriksa' => 36, 'urutan' => 1 ],
            [ 'id_juu' => 37, 'id_juu_pemeriksa' => 38, 'urutan' => 2 ],
            [ 'id_juu' => 32, 'id_juu_pemeriksa' => 36, 'urutan' => 1 ],
            [ 'id_juu' => 32, 'id_juu_pemeriksa' => 38, 'urutan' => 2 ],
            [ 'id_juu' => 54, 'id_juu_pemeriksa' => 57, 'urutan' => 1 ],
            [ 'id_juu' => 54, 'id_juu_pemeriksa' => 51, 'urutan' => 2 ],
            [ 'id_juu' => 33, 'id_juu_pemeriksa' => 30, 'urutan' => 1 ],
            [ 'id_juu' => 33, 'id_juu_pemeriksa' => 38, 'urutan' => 2 ],
            [ 'id_juu' => 78, 'id_juu_pemeriksa' => 95, 'urutan' => 1 ],
            [ 'id_juu' => 78, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 91, 'id_juu_pemeriksa' => 84, 'urutan' => 1 ],
            [ 'id_juu' => 91, 'id_juu_pemeriksa' => 95, 'urutan' => 2 ],
            [ 'id_juu' => 53, 'id_juu_pemeriksa' => 57, 'urutan' => 1 ],
            [ 'id_juu' => 53, 'id_juu_pemeriksa' => 51, 'urutan' => 2 ],
            [ 'id_juu' => 48, 'id_juu_pemeriksa' => 40, 'urutan' => 1 ],
            [ 'id_juu' => 48, 'id_juu_pemeriksa' => 41, 'urutan' => 2 ],
            [ 'id_juu' => 49, 'id_juu_pemeriksa' => 40, 'urutan' => 1 ],
            [ 'id_juu' => 49, 'id_juu_pemeriksa' => 41, 'urutan' => 2 ],
            [ 'id_juu' => 44, 'id_juu_pemeriksa' => 40, 'urutan' => 1 ],
            [ 'id_juu' => 44, 'id_juu_pemeriksa' => 41, 'urutan' => 2 ],
            [ 'id_juu' => 47, 'id_juu_pemeriksa' => 40, 'urutan' => 1 ],
            [ 'id_juu' => 47, 'id_juu_pemeriksa' => 41, 'urutan' => 2 ],
            [ 'id_juu' => 45, 'id_juu_pemeriksa' => 40, 'urutan' => 1 ],
            [ 'id_juu' => 45, 'id_juu_pemeriksa' => 41, 'urutan' => 2 ],
            [ 'id_juu' => 42, 'id_juu_pemeriksa' => 40, 'urutan' => 1 ],
            [ 'id_juu' => 42, 'id_juu_pemeriksa' => 41, 'urutan' => 2 ],
            [ 'id_juu' => 59, 'id_juu_pemeriksa' => 57, 'urutan' => 1 ],
            [ 'id_juu' => 59, 'id_juu_pemeriksa' => 51, 'urutan' => 2 ],
            [ 'id_juu' => 56, 'id_juu_pemeriksa' => 57, 'urutan' => 1 ],
            [ 'id_juu' => 56, 'id_juu_pemeriksa' => 51, 'urutan' => 2 ],
            [ 'id_juu' => 58, 'id_juu_pemeriksa' => 57, 'urutan' => 1 ],
            [ 'id_juu' => 58, 'id_juu_pemeriksa' => 51, 'urutan' => 2 ],
            [ 'id_juu' => 41, 'id_juu_pemeriksa' => 5, 'urutan' => 1 ],
            [ 'id_juu' => 41, 'id_juu_pemeriksa' => 1, 'urutan' => 2 ],
            [ 'id_juu' => 51, 'id_juu_pemeriksa' => 5, 'urutan' => 1 ],
            [ 'id_juu' => 51, 'id_juu_pemeriksa' => 1, 'urutan' => 2 ],
            [ 'id_juu' => 40, 'id_juu_pemeriksa' => 41, 'urutan' => 1 ],
            [ 'id_juu' => 40, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 43, 'id_juu_pemeriksa' => 41, 'urutan' => 1 ],
            [ 'id_juu' => 43, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 93, 'id_juu_pemeriksa' => 73, 'urutan' => 1 ],
            [ 'id_juu' => 93, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 96, 'id_juu_pemeriksa' => 73, 'urutan' => 1 ],
            [ 'id_juu' => 96, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 89, 'id_juu_pemeriksa' => 73, 'urutan' => 1 ],
            [ 'id_juu' => 89, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 83, 'id_juu_pemeriksa' => 73, 'urutan' => 1 ],
            [ 'id_juu' => 83, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 72, 'id_juu_pemeriksa' => 73, 'urutan' => 1 ],
            [ 'id_juu' => 72, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            // [ 'id_juu' => , 'id_juu_pemeriksa' => 73, 'urutan' => 1 ],
            // [ 'id_juu' => , 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 39, 'id_juu_pemeriksa' => 36, 'urutan' => 1 ],
            [ 'id_juu' => 39, 'id_juu_pemeriksa' => 38, 'urutan' => 2 ],
            [ 'id_juu' => 31, 'id_juu_pemeriksa' => 36, 'urutan' => 1 ],
            [ 'id_juu' => 31, 'id_juu_pemeriksa' => 38, 'urutan' => 2 ],
            [ 'id_juu' => 35, 'id_juu_pemeriksa' => 36, 'urutan' => 1 ],
            [ 'id_juu' => 35, 'id_juu_pemeriksa' => 38, 'urutan' => 2 ],
            [ 'id_juu' => 77, 'id_juu_pemeriksa' => 93, 'urutan' => 1 ],
            [ 'id_juu' => 77, 'id_juu_pemeriksa' => 73, 'urutan' => 2 ],
            [ 'id_juu' => 46, 'id_juu_pemeriksa' => 43, 'urutan' => 1 ],
            [ 'id_juu' => 46, 'id_juu_pemeriksa' => 41, 'urutan' => 2 ],
            [ 'id_juu' => 55, 'id_juu_pemeriksa' => 51, 'urutan' => 1 ],
            [ 'id_juu' => 55, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 57, 'id_juu_pemeriksa' => 51, 'urutan' => 1 ],
            [ 'id_juu' => 57, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 90, 'id_juu_pemeriksa' => 79, 'urutan' => 1 ],
            [ 'id_juu' => 90, 'id_juu_pemeriksa' => 75, 'urutan' => 2 ],
            [ 'id_juu' => 69, 'id_juu_pemeriksa' => 79, 'urutan' => 1 ],
            [ 'id_juu' => 69, 'id_juu_pemeriksa' => 67, 'urutan' => 2 ],
            [ 'id_juu' => 95, 'id_juu_pemeriksa' => 5, 'urutan' => 1 ],
            [ 'id_juu' => 95, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 70, 'id_juu_pemeriksa' => 5, 'urutan' => 1 ],
            [ 'id_juu' => 70, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 73, 'id_juu_pemeriksa' => 5, 'urutan' => 1 ],
            [ 'id_juu' => 73, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 98, 'id_juu_pemeriksa' => 5, 'urutan' => 1 ],
            [ 'id_juu' => 98, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 75, 'id_juu_pemeriksa' => 5, 'urutan' => 1 ],
            [ 'id_juu' => 75, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 84, 'id_juu_pemeriksa' => 95, 'urutan' => 1 ],
            [ 'id_juu' => 84, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 97, 'id_juu_pemeriksa' => 95, 'urutan' => 1 ],
            [ 'id_juu' => 97, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 18, 'id_juu_pemeriksa' => 8, 'urutan' => 1 ],
            [ 'id_juu' => 18, 'id_juu_pemeriksa' => 2, 'urutan' => 2 ],
            [ 'id_juu' => 24, 'id_juu_pemeriksa' => 8, 'urutan' => 1 ],
            [ 'id_juu' => 24, 'id_juu_pemeriksa' => 4, 'urutan' => 2 ],
            [ 'id_juu' => 74, 'id_juu_pemeriksa' => 8, 'urutan' => 1 ],
            [ 'id_juu' => 74, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 88, 'id_juu_pemeriksa' => 70, 'urutan' => 1 ],
            [ 'id_juu' => 88, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 92, 'id_juu_pemeriksa' => 70, 'urutan' => 1 ],
            [ 'id_juu' => 92, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 82, 'id_juu_pemeriksa' => 70, 'urutan' => 1 ],
            [ 'id_juu' => 82, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 100, 'id_juu_pemeriksa' => 70, 'urutan' => 1 ],
            [ 'id_juu' => 100, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 102, 'id_juu_pemeriksa' => 70, 'urutan' => 1 ],
            [ 'id_juu' => 102, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 86, 'id_juu_pemeriksa' => 98, 'urutan' => 1 ],
            [ 'id_juu' => 86, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 94, 'id_juu_pemeriksa' => 98, 'urutan' => 1 ],
            [ 'id_juu' => 94, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            // [ 'id_juu' => , 'id_juu_pemeriksa' => 98, 'urutan' => 1 ],
            // [ 'id_juu' => , 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            // [ 'id_juu' => , 'id_juu_pemeriksa' => 98, 'urutan' => 1 ],
            // [ 'id_juu' => , 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 80, 'id_juu_pemeriksa' => 74, 'urutan' => 1 ],
            [ 'id_juu' => 80, 'id_juu_pemeriksa' => 8, 'urutan' => 2 ],
            [ 'id_juu' => 85, 'id_juu_pemeriksa' => 74, 'urutan' => 1 ],
            [ 'id_juu' => 85, 'id_juu_pemeriksa' => 8, 'urutan' => 2 ],
            [ 'id_juu' => 66, 'id_juu_pemeriksa' => 74, 'urutan' => 1 ],
            [ 'id_juu' => 66, 'id_juu_pemeriksa' => 8, 'urutan' => 2 ],
            // [ 'id_juu' => , 'id_juu_pemeriksa' => 74, 'urutan' => 1 ],
            // [ 'id_juu' => , 'id_juu_pemeriksa' => 8, 'urutan' => 2 ],
            [ 'id_juu' => 87, 'id_juu_pemeriksa' => 9, 'urutan' => 1 ],
            [ 'id_juu' => 87, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 81, 'id_juu_pemeriksa' => 75, 'urutan' => 1 ],
            [ 'id_juu' => 81, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 79, 'id_juu_pemeriksa' => 75, 'urutan' => 1 ],
            [ 'id_juu' => 79, 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            // [ 'id_juu' => , 'id_juu_pemeriksa' => 75, 'urutan' => 1 ],
            // [ 'id_juu' => , 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            // [ 'id_juu' => , 'id_juu_pemeriksa' => 75, 'urutan' => 1 ],
            // [ 'id_juu' => , 'id_juu_pemeriksa' => 5, 'urutan' => 2 ],
            [ 'id_juu' => 67, 'id_juu_pemeriksa' => 6, 'urutan' => 1 ],
            [ 'id_juu' => 67, 'id_juu_pemeriksa' => 6, 'urutan' => 2 ],
            [ 'id_juu' => 68, 'id_juu_pemeriksa' => 6, 'urutan' => 1 ],
            [ 'id_juu' => 68, 'id_juu_pemeriksa' => 6, 'urutan' => 2 ],
            [ 'id_juu' => 62, 'id_juu_pemeriksa' => 6, 'urutan' => 1 ],
            [ 'id_juu' => 62, 'id_juu_pemeriksa' => 6, 'urutan' => 2 ],
            [ 'id_juu' => 65, 'id_juu_pemeriksa' => 6, 'urutan' => 1 ],
            [ 'id_juu' => 65, 'id_juu_pemeriksa' => 6, 'urutan' => 2 ],
            [ 'id_juu' => 60, 'id_juu_pemeriksa' => 67, 'urutan' => 1 ],
            [ 'id_juu' => 60, 'id_juu_pemeriksa' => 6, 'urutan' => 2 ],
            [ 'id_juu' => 64, 'id_juu_pemeriksa' => 67, 'urutan' => 1 ],
            [ 'id_juu' => 64, 'id_juu_pemeriksa' => 6, 'urutan' => 2 ],
            [ 'id_juu' => 61, 'id_juu_pemeriksa' => 67, 'urutan' => 1 ],
            [ 'id_juu' => 61, 'id_juu_pemeriksa' => 6, 'urutan' => 2 ],
            [ 'id_juu' => 63, 'id_juu_pemeriksa' => 67, 'urutan' => 1 ],
            [ 'id_juu' => 63, 'id_juu_pemeriksa' => 6, 'urutan' => 2 ],
            [ 'id_juu' => 4, 'id_juu_pemeriksa' => 1, 'urutan' => 1 ],
            [ 'id_juu' => 4, 'id_juu_pemeriksa' => 1, 'urutan' => 2 ],
            [ 'id_juu' => 6, 'id_juu_pemeriksa' => 1, 'urutan' => 1 ],
            [ 'id_juu' => 6, 'id_juu_pemeriksa' => 1, 'urutan' => 2 ],
            [ 'id_juu' => 10, 'id_juu_pemeriksa' => 14, 'urutan' => 1 ],
            [ 'id_juu' => 10, 'id_juu_pemeriksa' => 2, 'urutan' => 2 ],
            [ 'id_juu' => 19, 'id_juu_pemeriksa' => 14, 'urutan' => 1 ],
            [ 'id_juu' => 19, 'id_juu_pemeriksa' => 2, 'urutan' => 2 ],
            [ 'id_juu' => 99, 'id_juu_pemeriksa' => 86, 'urutan' => 1 ],
            [ 'id_juu' => 99, 'id_juu_pemeriksa' => 98, 'urutan' => 2 ],
            [ 'id_juu' => 101, 'id_juu_pemeriksa' => 72, 'urutan' => 1 ],
            [ 'id_juu' => 101, 'id_juu_pemeriksa' => 73, 'urutan' => 2 ],
            [ 'id_juu' => 103, 'id_juu_pemeriksa' => 88, 'urutan' => 1 ],
            [ 'id_juu' => 103, 'id_juu_pemeriksa' => 70, 'urutan' => 2 ],
            [ 'id_juu' => 76, 'id_juu_pemeriksa' => 82, 'urutan' => 1 ],
            [ 'id_juu' => 76, 'id_juu_pemeriksa' => 70, 'urutan' => 2 ],
            [ 'id_juu' => 106, 'id_juu_pemeriksa' => 21, 'urutan' => 1 ],
            [ 'id_juu' => 106, 'id_juu_pemeriksa' => 2, 'urutan' => 2 ],
        ]);
    }
}
