<?php
namespace Database\Seeders\Master;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class SeederTabelKota extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::connection('master_sys')->statement("TRUNCATE TABLE ONLY sys.kota RESTART IDENTITY CASCADE");
        DB::connection('master_sys')->table('kota')->insert([
            // BALI
            [ 'nama' => 'Badung', 'id_provinsi' => 1 ],
            [ 'nama' => 'Bangli', 'id_provinsi' => 1 ],
            [ 'nama' => 'Buleleng', 'id_provinsi' => 1 ],
            [ 'nama' => 'Denpasar', 'id_provinsi' => 1 ],
            [ 'nama' => 'Gianyar', 'id_provinsi' => 1 ],
            [ 'nama' => 'Jembrana', 'id_provinsi' => 1 ],
            [ 'nama' => 'Karangasem', 'id_provinsi' => 1 ],
            [ 'nama' => 'Klungkung', 'id_provinsi' => 1 ],
            [ 'nama' => 'Tabanan', 'id_provinsi' => 1 ],
            // BANGKA BELITUNG
            [ 'nama' => 'Bangka', 'id_provinsi' => 2 ],
            [ 'nama' => 'Bangka Barat', 'id_provinsi' => 2 ],
            [ 'nama' => 'Bangka Selatan', 'id_provinsi' => 2 ],
            [ 'nama' => 'Bangka Tengah', 'id_provinsi' => 2 ],
            [ 'nama' => 'Belitung', 'id_provinsi' => 2 ],
            [ 'nama' => 'Belitung Timur', 'id_provinsi' => 2 ],
            [ 'nama' => 'Pangkal Pinang', 'id_provinsi' => 2 ],
            // BANTEN
            [ 'nama' => 'Cilegon', 'id_provinsi' => 3 ],
            [ 'nama' => 'Lebak', 'id_provinsi' => 3 ],
            [ 'nama' => 'Pandeglang', 'id_provinsi' => 3 ],
            [ 'nama' => 'Kabupaten Serang', 'id_provinsi' => 3 ],
            [ 'nama' => 'Kota Serang', 'id_provinsi' => 3 ],
            [ 'nama' => 'Kabupaten Tangerang', 'id_provinsi' => 3 ],
            [ 'nama' => 'Kota Tangerang', 'id_provinsi' => 3 ],
            [ 'nama' => 'Tangerang Selatan', 'id_provinsi' => 3 ],
            // BENGKULU
            [ 'nama' => 'Bengkulu', 'id_provinsi' => 4 ],
            [ 'nama' => 'Bengkulu Selatan', 'id_provinsi' => 4 ],
            [ 'nama' => 'Bengkulu Tengah', 'id_provinsi' => 4 ],
            [ 'nama' => 'Bengkulu Utara', 'id_provinsi' => 4 ],
            [ 'nama' => 'Kaur', 'id_provinsi' => 4 ],
            [ 'nama' => 'Kepahiang', 'id_provinsi' => 4 ],
            [ 'nama' => 'Lebong', 'id_provinsi' => 4 ],
            [ 'nama' => 'Muko Muko', 'id_provinsi' => 4 ],
            [ 'nama' => 'Rejang Lebong', 'id_provinsi' => 4 ],
            [ 'nama' => 'Seluma', 'id_provinsi' => 4 ],
            // DI YOGYAKARTA
            [ 'nama' => 'Bantul', 'id_provinsi' => 5 ],
            [ 'nama' => 'Gunung Kidul', 'id_provinsi' => 5 ],
            [ 'nama' => 'Kulon Progo', 'id_provinsi' => 5 ],
            [ 'nama' => 'Sleman', 'id_provinsi' => 5 ],
            [ 'nama' => 'Yogyakarta', 'id_provinsi' => 5 ],
            // DKI JAKARTA
            [ 'nama' => 'Jakarta Barat', 'id_provinsi' => 6 ],
            [ 'nama' => 'Jakarta Pusat', 'id_provinsi' => 6 ],
            [ 'nama' => 'Jakarta Selatan', 'id_provinsi' => 6 ],
            [ 'nama' => 'Jakarta Timur', 'id_provinsi' => 6 ],
            [ 'nama' => 'Jakarta Utara', 'id_provinsi' => 6 ],
            [ 'nama' => 'Kepulauan Seribu', 'id_provinsi' => 6 ],
            // GORONTALO
            [ 'nama' => 'Boalemo', 'id_provinsi' => 7 ],
            [ 'nama' => 'Bone Bolango', 'id_provinsi' => 7 ],
            [ 'nama' => 'Kabupaten Gorontalo', 'id_provinsi' => 7 ],
            [ 'nama' => 'Kota Gorontalo', 'id_provinsi' => 7 ],
            [ 'nama' => 'Gorontalo Utara', 'id_provinsi' => 7 ],
            [ 'nama' => 'Pohuwato', 'id_provinsi' => 7 ],
            // JAMBI
            [ 'nama' => 'Batang Hari', 'id_provinsi' => 8 ],
            [ 'nama' => 'Bungo', 'id_provinsi' => 8 ],
            [ 'nama' => 'Jambi', 'id_provinsi' => 8 ],
            [ 'nama' => 'Kerinci', 'id_provinsi' => 8 ],
            [ 'nama' => 'Merangin', 'id_provinsi' => 8 ],
            [ 'nama' => 'Muaro Jambi', 'id_provinsi' => 8 ],
            [ 'nama' => 'Sarolangun', 'id_provinsi' => 8 ],
            [ 'nama' => 'Sungaipenuh', 'id_provinsi' => 8 ],
            [ 'nama' => 'Tanjung Jabung Barat', 'id_provinsi' => 8 ],
            [ 'nama' => 'Tanjung Jabung Timur', 'id_provinsi' => 8 ],
            [ 'nama' => 'Tebo', 'id_provinsi' => 8 ],
            // JAWA BARAT
            [ 'nama' => 'Kabupaten Bandung', 'id_provinsi' => 9 ],
            [ 'nama' => 'Kota Bandung', 'id_provinsi' => 9 ],
            [ 'nama' => 'Bandung Barat', 'id_provinsi' => 9 ],
            [ 'nama' => 'Banjar', 'id_provinsi' => 9 ],
            [ 'nama' => 'Kabupaten Bekasi', 'id_provinsi' => 9 ],
            [ 'nama' => 'Kota Bekasi', 'id_provinsi' => 9 ],
            [ 'nama' => 'Kabupaten Bogor', 'id_provinsi' => 9 ],
            [ 'nama' => 'Kota Bogor', 'id_provinsi' => 9 ],
            [ 'nama' => 'Ciamis', 'id_provinsi' => 9 ],
            [ 'nama' => 'Cianjur', 'id_provinsi' => 9 ],
            [ 'nama' => 'Cimahi', 'id_provinsi' => 9 ],
            [ 'nama' => 'Kabupaten Cirebon', 'id_provinsi' => 9 ],
            [ 'nama' => 'Kota Cirebon', 'id_provinsi' => 9 ],
            [ 'nama' => 'Depok', 'id_provinsi' => 9 ],
            [ 'nama' => 'Garut', 'id_provinsi' => 9 ],
            [ 'nama' => 'Indramayu', 'id_provinsi' => 9 ],
            [ 'nama' => 'Karawang', 'id_provinsi' => 9 ],
            [ 'nama' => 'Kuningan', 'id_provinsi' => 9 ],
            [ 'nama' => 'Majalengka', 'id_provinsi' => 9 ],
            [ 'nama' => 'Pangandaran', 'id_provinsi' => 9 ],
            [ 'nama' => 'Purwakarta', 'id_provinsi' => 9 ],
            [ 'nama' => 'Subang', 'id_provinsi' => 9 ],
            [ 'nama' => 'Kabupaten Sukabumi', 'id_provinsi' => 9 ],
            [ 'nama' => 'Kota Sukabumi', 'id_provinsi' => 9 ],
            [ 'nama' => 'Sumedang', 'id_provinsi' => 9 ],
            [ 'nama' => 'Kabupaten Tasikmalaya', 'id_provinsi' => 9 ],
            [ 'nama' => 'Kota Tasikmalaya', 'id_provinsi' => 9 ],
            // JAWA TENGAH
            [ 'nama' => 'Banjarnegara', 'id_provinsi' => 10 ],
            [ 'nama' => 'Banyumas', 'id_provinsi' => 10 ],
            [ 'nama' => 'Batang', 'id_provinsi' => 10 ],
            [ 'nama' => 'Blora', 'id_provinsi' => 10 ],
            [ 'nama' => 'Boyolali', 'id_provinsi' => 10 ],
            [ 'nama' => 'Brebes', 'id_provinsi' => 10 ],
            [ 'nama' => 'Cilacap', 'id_provinsi' => 10 ],
            [ 'nama' => 'Demak', 'id_provinsi' => 10 ],
            [ 'nama' => 'Grobogan', 'id_provinsi' => 10 ],
            [ 'nama' => 'Jepara', 'id_provinsi' => 10 ],
            [ 'nama' => 'Karanganyar', 'id_provinsi' => 10 ],
            [ 'nama' => 'Kebumen', 'id_provinsi' => 10 ],
            [ 'nama' => 'Kendal', 'id_provinsi' => 10 ],
            [ 'nama' => 'Klaten', 'id_provinsi' => 10 ],
            [ 'nama' => 'Kudus', 'id_provinsi' => 10 ],
            [ 'nama' => 'Kabupaten Magelang', 'id_provinsi' => 10 ],
            [ 'nama' => 'Kota Magelang', 'id_provinsi' => 10 ],
            [ 'nama' => 'Pati', 'id_provinsi' => 10 ],
            [ 'nama' => 'Kabupaten Pekalongan', 'id_provinsi' => 10 ],
            [ 'nama' => 'Kota Pekalongan', 'id_provinsi' => 10 ],
            [ 'nama' => 'Pemalang', 'id_provinsi' => 10 ],
            [ 'nama' => 'Purbalingga', 'id_provinsi' => 10 ],
            [ 'nama' => 'Purworejo', 'id_provinsi' => 10 ],
            [ 'nama' => 'Rembang', 'id_provinsi' => 10 ],
            [ 'nama' => 'Salatiga', 'id_provinsi' => 10 ],
            [ 'nama' => 'Kabupaten Semarang', 'id_provinsi' => 10 ],
            [ 'nama' => 'Kota Semarang', 'id_provinsi' => 10 ],
            [ 'nama' => 'Sragen', 'id_provinsi' => 10 ],
            [ 'nama' => 'Sukoharjo', 'id_provinsi' => 10 ],
            [ 'nama' => 'Surakarta (Solo)', 'id_provinsi' => 10 ],
            [ 'nama' => 'Kabupaten Tegal', 'id_provinsi' => 10 ],
            [ 'nama' => 'Kota Tegal', 'id_provinsi' => 10 ],
            [ 'nama' => 'Temanggung', 'id_provinsi' => 10 ],
            [ 'nama' => 'Wonogiri', 'id_provinsi' => 10 ],
            [ 'nama' => 'Wonosobo', 'id_provinsi' => 10 ],
            [ 'nama' => 'Purwokerto', 'id_provinsi' => 10 ],
            // JAWA TIMUR
            [ 'nama' => 'Bangkalan', 'id_provinsi' => 11 ],
            [ 'nama' => 'Banyuwangi', 'id_provinsi' => 11 ],
            [ 'nama' => 'Batu', 'id_provinsi' => 11 ],
            [ 'nama' => 'Kabupaten Blitar', 'id_provinsi' => 11 ],
            [ 'nama' => 'Kota Blitar', 'id_provinsi' => 11 ],
            [ 'nama' => 'Bojonegoro', 'id_provinsi' => 11 ],
            [ 'nama' => 'Bondowoso', 'id_provinsi' => 11 ],
            [ 'nama' => 'Gresik', 'id_provinsi' => 11 ],
            [ 'nama' => 'Jember', 'id_provinsi' => 11 ],
            [ 'nama' => 'Jombang', 'id_provinsi' => 11 ],
            [ 'nama' => 'Kabupaten Kediri', 'id_provinsi' => 11 ],
            [ 'nama' => 'Kota Kediri', 'id_provinsi' => 11 ],
            [ 'nama' => 'Lamongan', 'id_provinsi' => 11 ],
            [ 'nama' => 'Lumajang', 'id_provinsi' => 11 ],
            [ 'nama' => 'Kabupaten Madiun', 'id_provinsi' => 11 ],
            [ 'nama' => 'Kota Madiun', 'id_provinsi' => 11 ],
            [ 'nama' => 'Magetan', 'id_provinsi' => 11 ],
            [ 'nama' => 'Kabupaten Malang', 'id_provinsi' => 11 ],
            [ 'nama' => 'Kota Malang', 'id_provinsi' => 11 ],
            [ 'nama' => 'Kabupaten Mojokerto', 'id_provinsi' => 11 ],
            [ 'nama' => 'Kota Mojokerto', 'id_provinsi' => 11 ],
            [ 'nama' => 'Nganjuk', 'id_provinsi' => 11 ],
            [ 'nama' => 'Ngawi', 'id_provinsi' => 11 ],
            [ 'nama' => 'Pacitan', 'id_provinsi' => 11 ],
            [ 'nama' => 'Pamekasan', 'id_provinsi' => 11 ],
            [ 'nama' => 'Kabupaten Pasuruan', 'id_provinsi' => 11 ],
            [ 'nama' => 'Kota Pasuruan', 'id_provinsi' => 11 ],
            [ 'nama' => 'Ponorogo', 'id_provinsi' => 11 ],
            [ 'nama' => 'Kabupaten Probolinggo', 'id_provinsi' => 11 ],
            [ 'nama' => 'Kota Probolinggo', 'id_provinsi' => 11 ],
            [ 'nama' => 'Sampang', 'id_provinsi' => 11 ],
            [ 'nama' => 'Sidoarjo', 'id_provinsi' => 11 ],
            [ 'nama' => 'Situbondo', 'id_provinsi' => 11 ],
            [ 'nama' => 'Sumenep', 'id_provinsi' => 11 ],
            [ 'nama' => 'Surabaya', 'id_provinsi' => 11 ],
            [ 'nama' => 'Trenggalek', 'id_provinsi' => 11 ],
            [ 'nama' => 'Tuban', 'id_provinsi' => 11 ],
            [ 'nama' => 'Tulungagung', 'id_provinsi' => 11 ],
            // KALIMANTAN BARAT
            [ 'nama' => 'Bengkayang', 'id_provinsi' => 12 ],
            [ 'nama' => 'Kapuas Hulu', 'id_provinsi' => 12 ],
            [ 'nama' => 'Kayong Utara', 'id_provinsi' => 12 ],
            [ 'nama' => 'Ketapang', 'id_provinsi' => 12 ],
            [ 'nama' => 'Kubu Raya', 'id_provinsi' => 12 ],
            [ 'nama' => 'Landak', 'id_provinsi' => 12 ],
            [ 'nama' => 'Melawi', 'id_provinsi' => 12 ],
            [ 'nama' => 'Mempawah', 'id_provinsi' => 12 ],
            [ 'nama' => 'Pontianak', 'id_provinsi' => 12 ],
            [ 'nama' => 'Sambas', 'id_provinsi' => 12 ],
            [ 'nama' => 'Sanggau', 'id_provinsi' => 12 ],
            [ 'nama' => 'Sekadau', 'id_provinsi' => 12 ],
            [ 'nama' => 'Singkawang', 'id_provinsi' => 12 ],
            [ 'nama' => 'Sintang', 'id_provinsi' => 12 ],
            // KALIMANTAN SELATAN
            [ 'nama' => 'Balangan', 'id_provinsi' => 13 ],
            [ 'nama' => 'Banjar', 'id_provinsi' => 13 ],
            [ 'nama' => 'Banjarbaru', 'id_provinsi' => 13 ],
            [ 'nama' => 'Banjarmasin', 'id_provinsi' => 13 ],
            [ 'nama' => 'Barito Kuala', 'id_provinsi' => 13 ],
            [ 'nama' => 'Hulu Sungai Selatan', 'id_provinsi' => 13 ],
            [ 'nama' => 'Hulu Sungai Tengah', 'id_provinsi' => 13 ],
            [ 'nama' => 'Hulu Sungai Utara', 'id_provinsi' => 13 ],
            [ 'nama' => 'Kotabaru', 'id_provinsi' => 13 ],
            [ 'nama' => 'Tabalong', 'id_provinsi' => 13 ],
            [ 'nama' => 'Tanah Bumbu', 'id_provinsi' => 13 ],
            [ 'nama' => 'Tanah Laut', 'id_provinsi' => 13 ],
            [ 'nama' => 'Tapin', 'id_provinsi' => 13 ],
            // KALIMANTAN TENGAH
            [ 'nama' => 'Barito Selatan', 'id_provinsi' => 14 ],
            [ 'nama' => 'Barito Timur', 'id_provinsi' => 14 ],
            [ 'nama' => 'Barito Utara', 'id_provinsi' => 14 ],
            [ 'nama' => 'Gunung Mas', 'id_provinsi' => 14 ],
            [ 'nama' => 'Kapuas', 'id_provinsi' => 14 ],
            [ 'nama' => 'Katingan', 'id_provinsi' => 14 ],
            [ 'nama' => 'Kotawaringin Barat', 'id_provinsi' => 14 ],
            [ 'nama' => 'Kotawaringin Timur', 'id_provinsi' => 14 ],
            [ 'nama' => 'Lamandau', 'id_provinsi' => 14 ],
            [ 'nama' => 'Murung Raya', 'id_provinsi' => 14 ],
            [ 'nama' => 'Palangka Raya', 'id_provinsi' => 14 ],
            [ 'nama' => 'Pulang Pisau', 'id_provinsi' => 14 ],
            [ 'nama' => 'Seruyan', 'id_provinsi' => 14 ],
            [ 'nama' => 'Sukamara', 'id_provinsi' => 14 ],
            // KALIMANTAN TIMUR
            [ 'nama' => 'Balikpapan', 'id_provinsi' => 15 ],
            [ 'nama' => 'Berau', 'id_provinsi' => 15 ],
            [ 'nama' => 'Bontang', 'id_provinsi' => 15 ],
            [ 'nama' => 'Kutai Barat', 'id_provinsi' => 15 ],
            [ 'nama' => 'Kutai Kartanegara', 'id_provinsi' => 15 ],
            [ 'nama' => 'Kutai Timur', 'id_provinsi' => 15 ],
            [ 'nama' => 'Mahakam Ulu', 'id_provinsi' => 15 ],
            [ 'nama' => 'Paser', 'id_provinsi' => 15 ],
            [ 'nama' => 'Penajam Paser Utara', 'id_provinsi' => 15 ],
            [ 'nama' => 'Samarinda', 'id_provinsi' => 15 ],
            // KALIMANTAN UTARA
            [ 'nama' => 'Bulungan', 'id_provinsi' => 16 ],
            [ 'nama' => 'Malinau', 'id_provinsi' => 16 ],
            [ 'nama' => 'Nunukan', 'id_provinsi' => 16 ],
            [ 'nama' => 'Tana Tidung', 'id_provinsi' => 16 ],
            [ 'nama' => 'Tarakan', 'id_provinsi' => 16 ],
            // KEPULAUAN RIAU
            [ 'nama' => 'Batam', 'id_provinsi' => 17 ],
            [ 'nama' => 'Bintan', 'id_provinsi' => 17 ],
            [ 'nama' => 'Karimun', 'id_provinsi' => 17 ],
            [ 'nama' => 'Kepulauan Anambas', 'id_provinsi' => 17 ],
            [ 'nama' => 'Lingga', 'id_provinsi' => 17 ],
            [ 'nama' => 'Natuna', 'id_provinsi' => 17 ],
            [ 'nama' => 'Tanjung Pinang', 'id_provinsi' => 17 ],
            // LAMPUNG
            [ 'nama' => 'Bandar Lampung', 'id_provinsi' => 18 ],
            [ 'nama' => 'Lampung Barat', 'id_provinsi' => 18 ],
            [ 'nama' => 'Lampung Selatan', 'id_provinsi' => 18 ],
            [ 'nama' => 'Lampung Tengah', 'id_provinsi' => 18 ],
            [ 'nama' => 'Lampung Timur', 'id_provinsi' => 18 ],
            [ 'nama' => 'Lampung Utara', 'id_provinsi' => 18 ],
            [ 'nama' => 'Mesuji', 'id_provinsi' => 18 ],
            [ 'nama' => 'Metro', 'id_provinsi' => 18 ],
            [ 'nama' => 'Pesawaran', 'id_provinsi' => 18 ],
            [ 'nama' => 'Pesisir Barat', 'id_provinsi' => 18 ],
            [ 'nama' => 'Pringsewu', 'id_provinsi' => 18 ],
            [ 'nama' => 'Tanggamus', 'id_provinsi' => 18 ],
            [ 'nama' => 'Tulang Bawang', 'id_provinsi' => 18 ],
            [ 'nama' => 'Tulang Bawang Barat', 'id_provinsi' => 18 ],
            [ 'nama' => 'Way Kanan', 'id_provinsi' => 18 ],
            // MALUKU
            [ 'nama' => 'Ambon', 'id_provinsi' => 19 ],
            [ 'nama' => 'Buru', 'id_provinsi' => 19 ],
            [ 'nama' => 'Buru Selatan', 'id_provinsi' => 19 ],
            [ 'nama' => 'Kepulauan Aru', 'id_provinsi' => 19 ],
            [ 'nama' => 'Maluku Barat Daya', 'id_provinsi' => 19 ],
            [ 'nama' => 'Maluku Tengah', 'id_provinsi' => 19 ],
            [ 'nama' => 'Maluku Tenggara', 'id_provinsi' => 19 ],
            [ 'nama' => 'Maluku Tenggara Barat', 'id_provinsi' => 19 ],
            [ 'nama' => 'Seram Bagian Barat', 'id_provinsi' => 19 ],
            [ 'nama' => 'Seram Bagian Timur', 'id_provinsi' => 19 ],
            [ 'nama' => 'Tuai', 'id_provinsi' => 19 ],
            // MALUKU UTARA
            [ 'nama' => 'Halmahera Barat', 'id_provinsi' => 20 ],
            [ 'nama' => 'Halmahera Selatan', 'id_provinsi' => 20 ],
            [ 'nama' => 'Halmahera Tengah', 'id_provinsi' => 20 ],
            [ 'nama' => 'Halmahera Timur', 'id_provinsi' => 20 ],
            [ 'nama' => 'Halmahera Utara', 'id_provinsi' => 20 ],
            [ 'nama' => 'Kepulauan Sula', 'id_provinsi' => 20 ],
            [ 'nama' => 'Pulau Morotai', 'id_provinsi' => 20 ],
            [ 'nama' => 'Pulau Taliabu', 'id_provinsi' => 20 ],
            [ 'nama' => 'Ternate', 'id_provinsi' => 20 ],
            [ 'nama' => 'Tidore Kepulauan', 'id_provinsi' => 20 ],
            // NANGGROE ACEH DARUSSALAM
            [ 'nama' => 'Aceh Barat', 'id_provinsi' => 21 ],
            [ 'nama' => 'Aceh Barat Daya', 'id_provinsi' => 21 ],
            [ 'nama' => 'Aceh Besar', 'id_provinsi' => 21 ],
            [ 'nama' => 'Aceh Jaya', 'id_provinsi' => 21 ],
            [ 'nama' => 'Aceh Selatan', 'id_provinsi' => 21 ],
            [ 'nama' => 'Aceh Singkil', 'id_provinsi' => 21 ],
            [ 'nama' => 'Aceh Tamiang', 'id_provinsi' => 21 ],
            [ 'nama' => 'Aceh Tengah', 'id_provinsi' => 21 ],
            [ 'nama' => 'Aceh Tenggara', 'id_provinsi' => 21 ],
            [ 'nama' => 'Aceh Timur', 'id_provinsi' => 21 ],
            [ 'nama' => 'Aceh Utara', 'id_provinsi' => 21 ],
            [ 'nama' => 'Banda Aceh', 'id_provinsi' => 21 ],
            [ 'nama' => 'Bener Meriah', 'id_provinsi' => 21 ],
            [ 'nama' => 'Bireuen', 'id_provinsi' => 21 ],
            [ 'nama' => 'Gayo Lues', 'id_provinsi' => 21 ],
            [ 'nama' => 'Langsa', 'id_provinsi' => 21 ],
            [ 'nama' => 'Lhokseumawe', 'id_provinsi' => 21 ],
            [ 'nama' => 'Nagan Raya', 'id_provinsi' => 21 ],
            [ 'nama' => 'Pidie', 'id_provinsi' => 21 ],
            [ 'nama' => 'Pidie Jaya', 'id_provinsi' => 21 ],
            [ 'nama' => 'Sabang', 'id_provinsi' => 21 ],
            [ 'nama' => 'Simeulue', 'id_provinsi' => 21 ],
            [ 'nama' => 'Subulussalam', 'id_provinsi' => 21 ],
            // NUSA TENGGARA BARAT
            [ 'nama' => 'Kabupaten Bima', 'id_provinsi' => 22 ],
            [ 'nama' => 'Kota Bima', 'id_provinsi' => 22 ],
            [ 'nama' => 'Dompu', 'id_provinsi' => 22 ],
            [ 'nama' => 'Lombok Barat', 'id_provinsi' => 22 ],
            [ 'nama' => 'Lombok Tengah', 'id_provinsi' => 22 ],
            [ 'nama' => 'Lombok Timur', 'id_provinsi' => 22 ],
            [ 'nama' => 'Lombok Utara', 'id_provinsi' => 22 ],
            [ 'nama' => 'Mataram', 'id_provinsi' => 22 ],
            [ 'nama' => 'Sumbawa', 'id_provinsi' => 22 ],
            [ 'nama' => 'Sumbawa Barat', 'id_provinsi' => 22 ],
            // NUSA TENGGARA TIMUR
            [ 'nama' => 'Alor', 'id_provinsi' => 23 ],
            [ 'nama' => 'Belu', 'id_provinsi' => 23 ],
            [ 'nama' => 'Ende', 'id_provinsi' => 23 ],
            [ 'nama' => 'Flores Timur', 'id_provinsi' => 23 ],
            [ 'nama' => 'Kabupaten Kupang', 'id_provinsi' => 23 ],
            [ 'nama' => 'Kota Kupang', 'id_provinsi' => 23 ],
            [ 'nama' => 'Lembata', 'id_provinsi' => 23 ],
            [ 'nama' => 'Malaka', 'id_provinsi' => 23 ],
            [ 'nama' => 'Manggarai', 'id_provinsi' => 23 ],
            [ 'nama' => 'Manggarai Barat', 'id_provinsi' => 23 ],
            [ 'nama' => 'Manggarai Timur', 'id_provinsi' => 23 ],
            [ 'nama' => 'Nagekeo', 'id_provinsi' => 23 ],
            [ 'nama' => 'Ngada', 'id_provinsi' => 23 ],
            [ 'nama' => 'Rote Ndao', 'id_provinsi' => 23 ],
            [ 'nama' => 'Sabu Raijua', 'id_provinsi' => 23 ],
            [ 'nama' => 'Sikka', 'id_provinsi' => 23 ],
            [ 'nama' => 'Sumba Barat', 'id_provinsi' => 23 ],
            [ 'nama' => 'Sumba Barat Daya', 'id_provinsi' => 23 ],
            [ 'nama' => 'Sumba Tengah', 'id_provinsi' => 23 ],
            [ 'nama' => 'Sumba Timur', 'id_provinsi' => 23 ],
            [ 'nama' => 'Timor Tengah Selatan', 'id_provinsi' => 23 ],
            [ 'nama' => 'Timor Tengah Utara', 'id_provinsi' => 23 ],
            // PAPUA
            [ 'nama' => 'Asmat', 'id_provinsi' => 24 ],
            [ 'nama' => 'Biak Numfor', 'id_provinsi' => 24 ],
            [ 'nama' => 'Boven Digoel', 'id_provinsi' => 24 ],
            [ 'nama' => 'Deiyai', 'id_provinsi' => 24 ],
            [ 'nama' => 'Dogiyai', 'id_provinsi' => 24 ],
            [ 'nama' => 'Intan Jaya', 'id_provinsi' => 24 ],
            [ 'nama' => 'Kabupaten Jayapura', 'id_provinsi' => 24 ],
            [ 'nama' => 'Kota Jayapura', 'id_provinsi' => 24 ],
            [ 'nama' => 'Jayawijaya', 'id_provinsi' => 24 ],
            [ 'nama' => 'Keerom', 'id_provinsi' => 24 ],
            [ 'nama' => 'Kepulauan Yapen', 'id_provinsi' => 24 ],
            [ 'nama' => 'Lanny Jaya', 'id_provinsi' => 24 ],
            [ 'nama' => 'Mamberamo Raya', 'id_provinsi' => 24 ],
            [ 'nama' => 'Mamberamo Tengah', 'id_provinsi' => 24 ],
            [ 'nama' => 'Mappi', 'id_provinsi' => 24 ],
            [ 'nama' => 'Merauke', 'id_provinsi' => 24 ],
            [ 'nama' => 'Mimika', 'id_provinsi' => 24 ],
            [ 'nama' => 'Nabire', 'id_provinsi' => 24 ],
            [ 'nama' => 'Nduga', 'id_provinsi' => 24 ],
            [ 'nama' => 'Paniai', 'id_provinsi' => 24 ],
            [ 'nama' => 'Pegunungan Bintang', 'id_provinsi' => 24 ],
            [ 'nama' => 'Puncak', 'id_provinsi' => 24 ],
            [ 'nama' => 'Puncak Jaya', 'id_provinsi' => 24 ],
            [ 'nama' => 'Sarmi', 'id_provinsi' => 24 ],
            [ 'nama' => 'Supiori', 'id_provinsi' => 24 ],
            [ 'nama' => 'Tolikara', 'id_provinsi' => 24 ],
            [ 'nama' => 'Waropen', 'id_provinsi' => 24 ],
            [ 'nama' => 'Yahukimo', 'id_provinsi' => 24 ],
            [ 'nama' => 'Yalimo', 'id_provinsi' => 24 ],
            // PAPUA BARAT
            [ 'nama' => 'Fakfak', 'id_provinsi' => 25 ],
            [ 'nama' => 'Kaimana', 'id_provinsi' => 25 ],
            [ 'nama' => 'Manokwari', 'id_provinsi' => 25 ],
            [ 'nama' => 'Manokwari Selatan', 'id_provinsi' => 25 ],
            [ 'nama' => 'Maybrat', 'id_provinsi' => 25 ],
            [ 'nama' => 'Pegunungan Arfak', 'id_provinsi' => 25 ],
            [ 'nama' => 'Raja Ampat', 'id_provinsi' => 25 ],
            [ 'nama' => 'Kabupaten Sorong', 'id_provinsi' => 25 ],
            [ 'nama' => 'Kota Sorong', 'id_provinsi' => 25 ],
            [ 'nama' => 'Sorong Selatan', 'id_provinsi' => 25 ],
            [ 'nama' => 'Tambrauw', 'id_provinsi' => 25 ],
            [ 'nama' => 'Teluk Bintuni', 'id_provinsi' => 25 ],
            [ 'nama' => 'Teluk Wondama', 'id_provinsi' => 25 ],
            // RIAU
            [ 'nama' => 'Bengkalis', 'id_provinsi' => 26 ],
            [ 'nama' => 'Dumai', 'id_provinsi' => 26 ],
            [ 'nama' => 'Indragiri Hilir', 'id_provinsi' => 26 ],
            [ 'nama' => 'Indragiri Hulu', 'id_provinsi' => 26 ],
            [ 'nama' => 'Kampar', 'id_provinsi' => 26 ],
            [ 'nama' => 'Kepulauan Meranti', 'id_provinsi' => 26 ],
            [ 'nama' => 'Kuantan Singingi', 'id_provinsi' => 26 ],
            [ 'nama' => 'Pekanbaru', 'id_provinsi' => 26 ],
            [ 'nama' => 'Pelalawan', 'id_provinsi' => 26 ],
            [ 'nama' => 'Rokan Hilir', 'id_provinsi' => 26 ],
            [ 'nama' => 'Rokan Hulu', 'id_provinsi' => 26 ],
            [ 'nama' => 'Siak', 'id_provinsi' => 26 ],
            // SULAWESI BARAT
            [ 'nama' => 'Majene', 'id_provinsi' => 27 ],
            [ 'nama' => 'Mamasa', 'id_provinsi' => 27 ],
            [ 'nama' => 'Mamuju', 'id_provinsi' => 27 ],
            [ 'nama' => 'Mamuju Tengah', 'id_provinsi' => 27 ],
            [ 'nama' => 'Mamuju Utara', 'id_provinsi' => 27 ],
            [ 'nama' => 'Polewali Mandar', 'id_provinsi' => 27 ],
            // SULAWESI SELATAN
            [ 'nama' => 'Bantaeng', 'id_provinsi' => 28 ],
            [ 'nama' => 'Barru', 'id_provinsi' => 28 ],
            [ 'nama' => 'Bone', 'id_provinsi' => 28 ],
            [ 'nama' => 'Bulukumba', 'id_provinsi' => 28 ],
            [ 'nama' => 'Enrekang', 'id_provinsi' => 28 ],
            [ 'nama' => 'Gowa', 'id_provinsi' => 28 ],
            [ 'nama' => 'Jeneponto', 'id_provinsi' => 28 ],
            [ 'nama' => 'Kepulauan Selayar', 'id_provinsi' => 28 ],
            [ 'nama' => 'Luwu', 'id_provinsi' => 28 ],
            [ 'nama' => 'Luwu Timur', 'id_provinsi' => 28 ],
            [ 'nama' => 'Luwu Utara', 'id_provinsi' => 28 ],
            [ 'nama' => 'Makassar (Ujung Pandang)', 'id_provinsi' => 28 ],
            [ 'nama' => 'Maros', 'id_provinsi' => 28 ],
            [ 'nama' => 'Palopo', 'id_provinsi' => 28 ],
            [ 'nama' => 'Pangkajene Kepulauan', 'id_provinsi' => 28 ],
            [ 'nama' => 'Parepare', 'id_provinsi' => 28 ],
            [ 'nama' => 'Pinrang', 'id_provinsi' => 28 ],
            [ 'nama' => 'Sidenreng Rappang', 'id_provinsi' => 28 ],
            [ 'nama' => 'Sinjai', 'id_provinsi' => 28 ],
            [ 'nama' => 'Soppeng', 'id_provinsi' => 28 ],
            [ 'nama' => 'Takalar', 'id_provinsi' => 28 ],
            [ 'nama' => 'Tana Toraja', 'id_provinsi' => 28 ],
            [ 'nama' => 'Toraja Utara', 'id_provinsi' => 28 ],
            [ 'nama' => 'Wajo', 'id_provinsi' => 28 ],
            // SULAWESI TENGAH
            [ 'nama' => 'Banggai', 'id_provinsi' => 29 ],
            [ 'nama' => 'Banggai Kepulauan', 'id_provinsi' => 29 ],
            [ 'nama' => 'Banggai Laut', 'id_provinsi' => 29 ],
            [ 'nama' => 'Buol', 'id_provinsi' => 29 ],
            [ 'nama' => 'Donggala', 'id_provinsi' => 29 ],
            [ 'nama' => 'Morowali', 'id_provinsi' => 29 ],
            [ 'nama' => 'Morowali Utara', 'id_provinsi' => 29 ],
            [ 'nama' => 'Palu', 'id_provinsi' => 29 ],
            [ 'nama' => 'Parigi Moutong', 'id_provinsi' => 29 ],
            [ 'nama' => 'Poso', 'id_provinsi' => 29 ],
            [ 'nama' => 'Sigi', 'id_provinsi' => 29 ],
            [ 'nama' => 'Tojo Una-Una', 'id_provinsi' => 29 ],
            [ 'nama' => 'Toli-Toli', 'id_provinsi' => 29 ],
            // SULAWESI TENGGARA
            [ 'nama' => 'Bau-Bau', 'id_provinsi' => 30 ],
            [ 'nama' => 'Bombana', 'id_provinsi' => 30 ],
            [ 'nama' => 'Buton', 'id_provinsi' => 30 ],
            [ 'nama' => 'Buton Selatan', 'id_provinsi' => 30 ],
            [ 'nama' => 'Buton Tengah', 'id_provinsi' => 30 ],
            [ 'nama' => 'Buton Utara', 'id_provinsi' => 30 ],
            [ 'nama' => 'Kendari', 'id_provinsi' => 30 ],
            [ 'nama' => 'Kolaka', 'id_provinsi' => 30 ],
            [ 'nama' => 'Kolaka Timur', 'id_provinsi' => 30 ],
            [ 'nama' => 'Kolaka Utara', 'id_provinsi' => 30 ],
            [ 'nama' => 'Konawe', 'id_provinsi' => 30 ],
            [ 'nama' => 'Konawe Kepulauan', 'id_provinsi' => 30 ],
            [ 'nama' => 'Konawe Selatan', 'id_provinsi' => 30 ],
            [ 'nama' => 'Konawe Utara', 'id_provinsi' => 30 ],
            [ 'nama' => 'Muna', 'id_provinsi' => 30 ],
            [ 'nama' => 'Muna Barat', 'id_provinsi' => 30 ],
            [ 'nama' => 'Wakatobi', 'id_provinsi' => 30 ],
            // SULAWESI UTARA
            [ 'nama' => 'Bitung', 'id_provinsi' => 31 ],
            [ 'nama' => 'Bolaang Mongondow', 'id_provinsi' => 31 ],
            [ 'nama' => 'Bolaang Mongondow Selatan', 'id_provinsi' => 31 ],
            [ 'nama' => 'Bolaang Mongondow Timur', 'id_provinsi' => 31 ],
            [ 'nama' => 'Bolaang Mongondow Utara', 'id_provinsi' => 31 ],
            [ 'nama' => 'Kepulauan Sangihe', 'id_provinsi' => 31 ],
            [ 'nama' => 'Siau Tagulandang Biaro', 'id_provinsi' => 31 ],
            [ 'nama' => 'Kepulauan Talaud', 'id_provinsi' => 31 ],
            [ 'nama' => 'Kotamobagu', 'id_provinsi' => 31 ],
            [ 'nama' => 'Manado', 'id_provinsi' => 31 ],
            [ 'nama' => 'Minahasa', 'id_provinsi' => 31 ],
            [ 'nama' => 'Minahasa Selatan', 'id_provinsi' => 31 ],
            [ 'nama' => 'Minahasa Tenggara', 'id_provinsi' => 31 ],
            [ 'nama' => 'Minahasa Utara', 'id_provinsi' => 31 ],
            [ 'nama' => 'Tomohon', 'id_provinsi' => 31 ],
            // SUMATERA BARAT
            [ 'nama' => 'Agam', 'id_provinsi' => 32 ],
            [ 'nama' => 'Bukitinggi', 'id_provinsi' => 32 ],
            [ 'nama' => 'Dharmasraya', 'id_provinsi' => 32 ],
            [ 'nama' => 'Kepulauan Mentawai', 'id_provinsi' => 32 ],
            [ 'nama' => 'Lima Puluh Kota', 'id_provinsi' => 32 ],
            [ 'nama' => 'Padang', 'id_provinsi' => 32 ],
            [ 'nama' => 'Padang Panjang', 'id_provinsi' => 32 ],
            [ 'nama' => 'Padang Pariaman', 'id_provinsi' => 32 ],
            [ 'nama' => 'Pariaman', 'id_provinsi' => 32 ],
            [ 'nama' => 'Pasaman', 'id_provinsi' => 32 ],
            [ 'nama' => 'Pasaman Barat', 'id_provinsi' => 32 ],
            [ 'nama' => 'Payakumbuh', 'id_provinsi' => 32 ],
            [ 'nama' => 'Pesisir Selatan', 'id_provinsi' => 32 ],
            [ 'nama' => 'Sawah Lunto', 'id_provinsi' => 32 ],
            [ 'nama' => 'Sijunjung', 'id_provinsi' => 32 ],
            [ 'nama' => 'Kabupaten Solok', 'id_provinsi' => 32 ],
            [ 'nama' => 'Kota Solok', 'id_provinsi' => 32 ],
            [ 'nama' => 'Solok Selatan', 'id_provinsi' => 32 ],
            [ 'nama' => 'Tanah Datar', 'id_provinsi' => 32 ],
            // SUMATERA SELATAN
            [ 'nama' => 'Banyuasin', 'id_provinsi' => 33 ],
            [ 'nama' => 'Empat Lawang', 'id_provinsi' => 33 ],
            [ 'nama' => 'Lahat', 'id_provinsi' => 33 ],
            [ 'nama' => 'Lubuk Linggau', 'id_provinsi' => 33 ],
            [ 'nama' => 'Muara Enim', 'id_provinsi' => 33 ],
            [ 'nama' => 'Musi Banyuasin', 'id_provinsi' => 33 ],
            [ 'nama' => 'Musi Rawas', 'id_provinsi' => 33 ],
            [ 'nama' => 'Musi Rawas Utara', 'id_provinsi' => 33 ],
            [ 'nama' => 'Ogan Ilir', 'id_provinsi' => 33 ],
            [ 'nama' => 'Ogan Komering Ilir', 'id_provinsi' => 33 ],
            [ 'nama' => 'Ogan Komering Ulu', 'id_provinsi' => 33 ],
            [ 'nama' => 'Ogan Komering Ulu Selatan', 'id_provinsi' => 33 ],
            [ 'nama' => 'Ogan Komering Ulu Timur', 'id_provinsi' => 33 ],
            [ 'nama' => 'Pagar Alam', 'id_provinsi' => 33 ],
            [ 'nama' => 'Palembang', 'id_provinsi' => 33 ],
            [ 'nama' => 'Penukal Abab Lematang Ilir', 'id_provinsi' => 33 ],
            [ 'nama' => 'Prabumulih', 'id_provinsi' => 33 ],
            [ 'nama' => 'Martapura', 'id_provinsi' => 33 ],
            // SUMATERA UTARA
            [ 'nama' => 'Asahan', 'id_provinsi' => 34 ],
            [ 'nama' => 'Batu Bara', 'id_provinsi' => 34 ],
            [ 'nama' => 'Binjai', 'id_provinsi' => 34 ],
            [ 'nama' => 'Dairi', 'id_provinsi' => 34 ],
            [ 'nama' => 'Deli Serdang', 'id_provinsi' => 34 ],
            [ 'nama' => 'Gunungsitoli', 'id_provinsi' => 34 ],
            [ 'nama' => 'Humbang Hasundutan', 'id_provinsi' => 34 ],
            [ 'nama' => 'Karo', 'id_provinsi' => 34 ],
            [ 'nama' => 'Labuhanbatu', 'id_provinsi' => 34 ],
            [ 'nama' => 'Labuhanbatu Selatan', 'id_provinsi' => 34 ],
            [ 'nama' => 'Labuhanbatu Utara', 'id_provinsi' => 34 ],
            [ 'nama' => 'Langkat', 'id_provinsi' => 34 ],
            [ 'nama' => 'Mandailing Natal', 'id_provinsi' => 34 ],
            [ 'nama' => 'Medan', 'id_provinsi' => 34 ],
            [ 'nama' => 'Nias', 'id_provinsi' => 34 ],
            [ 'nama' => 'Nias Barat', 'id_provinsi' => 34 ],
            [ 'nama' => 'Nias Selatan', 'id_provinsi' => 34 ],
            [ 'nama' => 'Nias Utara', 'id_provinsi' => 34 ],
            [ 'nama' => 'Padang Lawas', 'id_provinsi' => 34 ],
            [ 'nama' => 'Padang Lawas Utara', 'id_provinsi' => 34 ],
            [ 'nama' => 'Padang Sidempuan', 'id_provinsi' => 34 ],
            [ 'nama' => 'Pakpak Bharat', 'id_provinsi' => 34 ],
            [ 'nama' => 'Pematang Siantar', 'id_provinsi' => 34 ],
            [ 'nama' => 'Samosir', 'id_provinsi' => 34 ],
            [ 'nama' => 'Serdang Bedagai', 'id_provinsi' => 34 ],
            [ 'nama' => 'Sibolga', 'id_provinsi' => 34 ],
            [ 'nama' => 'Simalungun', 'id_provinsi' => 34 ],
            [ 'nama' => 'Tanjung Balai', 'id_provinsi' => 34 ],
            [ 'nama' => 'Tapanuli Selatan', 'id_provinsi' => 34 ],
            [ 'nama' => 'Tapanuli Tengah', 'id_provinsi' => 34 ],
            [ 'nama' => 'Tapanuli Utara', 'id_provinsi' => 34 ],
            [ 'nama' => 'Tebing Tinggi', 'id_provinsi' => 34 ],
            [ 'nama' => 'Toba Samosir', 'id_provinsi' => 34 ],
        ]);
    }
}
