<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class SeederTabelKaryawan extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::connection('master_sys')->statement("TRUNCATE TABLE ONLY sys.karyawan RESTART IDENTITY CASCADE");
        DB::connection('master_sys')->table('karyawan')->insert([
            [
                'id_user' => 1,
                // 'nama' => 'Agus Nurwahyudi',
                'nik' => '1JA100001',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 10,
                'status_tanggungan' => NULL,
                'no_npwp' => NULL,
                'no_bpjs_tenaga_kerja' => NULL,
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => NULL,
                'tanggal_pensiun' => NULL,
                'sisa_masa_kerja' => NULL,
                'id_bank_payroll' => 3,
                'no_bank_payroll' => '024 4985 228'
            ],
            [
                'id_user' => 2,
                // 'nama' => 'Yasin Rizal',
                'nik' => '0884032J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 10,
                'status_tanggungan' => 7,
                'no_npwp' => '24.817.293.4-014.000',
                'no_bpjs_tenaga_kerja' => '08004089978',
                'no_bpjs_kesehatan' => '0002358499408',
                'tanggal_masuk' => '2008-02-01',
                'tanggal_pensiun' => Carbon::parse('1984-08-09')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1984-08-09')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01 001179 56 5'
            ],
            [
                'id_user' => 3,
                // 'nama' => 'Noer Gumilar Noviardhi',
                'nik' => '0480008J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 8,
                'status_tanggungan' => 7,
                'no_npwp' => '24.085.011.5-411.000',
                'no_bpjs_tenaga_kerja' => '03JD0028452',
                'no_bpjs_kesehatan' => '0002234292838',
                'tanggal_masuk' => '2004-02-01',
                'tanggal_pensiun' => Carbon::parse('1980-11-15')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1980-11-15')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01074251 50 8'
            ],
            [
                'id_user' => 4,
                // 'nama' => 'Peggy Rosa',
                'nik' => '1178047J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 8,
                'status_tanggungan' => 1,
                'no_npwp' => '47.063.406.4-008.000',
                'no_bpjs_tenaga_kerja' => '11038434491',
                'no_bpjs_kesehatan' => '0002234305236',
                'tanggal_masuk' => '2011-06-01',
                'tanggal_pensiun' => Carbon::parse('1978-05-01')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1978-05-01')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01 078360 50 3'
            ],
            [
                'id_user' => 5,
                // 'nama' => 'Gadis Anindya Ayu Widiasari',
                'nik' => '0482006J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 5,
                'status_tanggungan' => 1,
                'no_npwp' => '48.670.873.8-002.000',
                'no_bpjs_tenaga_kerja' => '04JD0031876',
                'no_bpjs_kesehatan' => '0002234308926',
                'tanggal_masuk' => '2004-02-01',
                'tanggal_pensiun' => Carbon::parse('1982-09-24')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1982-09-24')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01070309 50 3'
            ],
            [
                'id_user' => 6,
                // 'nama' => 'Ana Malini',
                'nik' => '1888100J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '34.637.145.3-435.000',
                'no_bpjs_tenaga_kerja' => '18055116968',
                'no_bpjs_kesehatan' => '0001635825969',
                'tanggal_masuk' => '2018-07-02',
                'tanggal_pensiun' => Carbon::parse('1988-04-27')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1988-04-27')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01 150483 50 2'
            ],
            [
                'id_user' => 7,
                // 'nama' => 'Hari Wibowo',
                'nik' => '0684021J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 5,
                'status_tanggungan' => 7,
                'no_npwp' => '24.701.475.6-451.000',
                'no_bpjs_tenaga_kerja' => '07001863203',
                'no_bpjs_kesehatan' => '0002234384188',
                'tanggal_masuk' => '2006-05-01',
                'tanggal_pensiun' => Carbon::parse('1984-05-02')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1984-05-02')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01070236 50 6'
            ],
            [
                'id_user' => 8,
                // 'nama' => 'Nadia Suwandy',
                'nik' => '1691083J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 1,
                'no_npwp' => '66.562.189.2-306.000',
                'no_bpjs_tenaga_kerja' => '17003052630',
                'no_bpjs_kesehatan' => '0001378466008',
                'tanggal_masuk' => '2016-08-01',
                'tanggal_pensiun' => Carbon::parse('1991-01-12')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1991-01-12')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206-01-128442-50-6'
            ],
            [
                'id_user' => 9,
                // 'nama' => 'Sri Maryati',
                'nik' => '1489058J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 1,
                'no_npwp' => '71.047.450.3-426.000',
                'no_bpjs_tenaga_kerja' => '11035025540',
                'no_bpjs_kesehatan' => '0002358461889',
                'tanggal_masuk' => '2014-04-01',
                'tanggal_pensiun' => Carbon::parse('1989-02-19')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1989-02-19')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01 086710 50 6'
            ],
            [
                'id_user' => 10,
                // 'nama' => 'Enjang',
                'nik' => '0383005J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 7,
                'no_npwp' => '24.702.143.9-434.000',
                'no_bpjs_tenaga_kerja' => '04JD0031892',
                'no_bpjs_kesehatan' => '0002234393526',
                'tanggal_masuk' => '2003-07-01',
                'tanggal_pensiun' => Carbon::parse('1982-09-13')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1982-09-13')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01070246 50 1'
            ],
            [
                'id_user' => 11,
                // 'nama' => 'Nur Ardhiansyah',
                'nik' => '1694082J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '70.092.962.3-529.000',
                'no_bpjs_tenaga_kerja' => '17003052648',
                'no_bpjs_kesehatan' => '0001964266885',
                'tanggal_masuk' => '2016-07-01',
                'tanggal_pensiun' => Carbon::parse('1994-02-02')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1994-02-02')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '3724 01 000300 50 2'
            ],
            [
                'id_user' => 12,
                // 'nama' => 'Heri Setiawan',
                'nik' => '1882101J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 7,
                'no_npwp' => '57.278.1482-411.000',
                'no_bpjs_tenaga_kerja' => '14024372402',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2018-07-16',
                'tanggal_pensiun' => Carbon::parse('1982-03-30')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1982-03-30')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206-01-151706-50-5'
            ],
            [
                'id_user' => 13,
                // 'nama' => 'Shella',
                'nik' => '1590062J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 1,
                'no_npwp' => '57.656.985.9-048.000',
                'no_bpjs_tenaga_kerja' => '15031108036',
                'no_bpjs_kesehatan' => '0002358461878',
                'tanggal_masuk' => '2015-02-01',
                'tanggal_pensiun' => Carbon::parse('1990-10-10')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1990-10-10')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01 107612 50 0'
            ],
            [
                'id_user' => 14,
                // 'nama' => 'Siti Fatimah',
                'nik' => '1376056J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 1,
                'no_npwp' => '24.439.537.2-412.001',
                'no_bpjs_tenaga_kerja' => '14000597121',
                'no_bpjs_kesehatan' => '0002354909084',
                'tanggal_masuk' => '2013-12-01',
                'tanggal_pensiun' => Carbon::parse('1976-03-10')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1976-03-10')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01 086481 50 5'
            ],
            [
                'id_user' => 15,
                // 'nama' => 'Edwin Basten Matualaga',
                'nik' => '1688081J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 3,
                'status_tanggungan' => 5,
                'no_npwp' => '26.059.092.0-412.000',
                'no_bpjs_tenaga_kerja' => '17003052705',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2016-07-01',
                'tanggal_pensiun' => Carbon::parse('1988-06-15')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1988-06-15')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0796-01-002792-50-9'
            ],
            [
                'id_user' => 16,
                // 'nama' => 'Antonius Nova Kunfianto',
                'nik' => '1083043C',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 6,
                'status_tanggungan' => 7,
                'no_npwp' => '68.357.028.7-522.000',
                'no_bpjs_tenaga_kerja' => '05L20076549',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2010-03-01',
                'tanggal_pensiun' => Carbon::parse('1983-11-27')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1983-11-27')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032746 50 7'
            ],
            [
                'id_user' => 17,
                // 'nama' => 'Suharman Rosuli',
                'nik' => '1487059J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 7,
                'no_npwp' => '69.966.010.6-403.000',
                'no_bpjs_tenaga_kerja' => '14010839901',
                'no_bpjs_kesehatan' => '0001281848229',
                'tanggal_masuk' => '2014-04-01',
                'tanggal_pensiun' => Carbon::parse('1987-09-07')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1987-09-07')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01 095949 50 8'
            ],
            [
                'id_user' => 18,
                // 'nama' => 'Gina Novianti',
                'nik' => '0983033J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 1,
                'no_npwp' => '26.840.717.8-013.000',
                'no_bpjs_tenaga_kerja' => '09010688134',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2009-05-01',
                'tanggal_pensiun' => Carbon::parse('1983-11-19')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1983-11-19')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01070274 50 4'
            ],
            [
                'id_user' => 19,
                // 'nama' => 'Arri Pradipta',
                'nik' => '0778029J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 6,
                'status_tanggungan' => 1,
                'no_npwp' => '14.261.005.4-606.000',
                'no_bpjs_tenaga_kerja' => '04JD0031868',
                'no_bpjs_kesehatan' => '0002234373129',
                'tanggal_masuk' => '2007-06-01',
                'tanggal_pensiun' => Carbon::parse('1978-04-15')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1978-04-15')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01 073535 50 1'
            ],
            [
                'id_user' => 20,
                // 'nama' => 'Syafriyanzah',
                'nik' => '1890099J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '70.328.722.7-804.000',
                'no_bpjs_tenaga_kerja' => '18055116976',
                'no_bpjs_kesehatan' => '0001375719693',
                'tanggal_masuk' => '2018-07-02',
                'tanggal_pensiun' => Carbon::parse('1990-06-30')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1990-06-30')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0343 01 031792 50 1'
            ],
            [
                'id_user' => 21,
                // 'nama' => 'Adias Purnomo',
                'nik' => '0985036J',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 5,
                'status_tanggungan' => 7,
                'no_npwp' => '57.311.375.0-543.000',
                'no_bpjs_tenaga_kerja' => '10023433724',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2009-11-01',
                'tanggal_pensiun' => Carbon::parse('1985-05-06')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1985-05-06')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '3008 01000220 50 2'
            ],
            [
                'id_user' => 22,
                // 'nama' => 'Irvan Rahmat',
                'nik' => '0671022C',
                'id_kota_kerja' => 96,
                'id_unit' => 1,
                'id_level_karyawan' => 10,
                'status_tanggungan' => 8,
                'no_npwp' => '05.873.769.3-522.000',
                'no_bpjs_tenaga_kerja' => NULL,
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2005-12-01',
                'tanggal_pensiun' => Carbon::parse('1971-01-26')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1971-01-26')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032756 50 2'
            ],
            [
                'id_user' => 23,
                // 'nama' => 'Ferdika Hindradi',
                'nik' => '0573018J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 7,
                'status_tanggungan' => 7,
                'no_npwp' => '17.612.885.8-017.000',
                'no_bpjs_tenaga_kerja' => '02J60100951',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2005-05-01',
                'tanggal_pensiun' => Carbon::parse('1973-06-17')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1973-06-17')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 4,
                'no_bank_payroll' => '0811510817'
            ],
            [
                'id_user' => 24,
                // 'nama' => 'Sugeng',
                'nik' => '1471060C',
                'id_kota_kerja' => 96,
                'id_unit' => 2,
                'id_level_karyawan' => 8,
                'status_tanggungan' => 6,
                'no_npwp' => '07.886.294.3-612.000',
                'no_bpjs_tenaga_kerja' => NULL,
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2014-05-01',
                'tanggal_pensiun' => Carbon::parse('1971-08-05')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1971-08-05')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 034994 50 4'
            ],
            [
                'id_user' => 25,
                // 'nama' => 'R. Indra Arisyanto',
                'nik' => '1679072C',
                'id_kota_kerja' => 96,
                'id_unit' => 2,
                'id_level_karyawan' => 6,
                'status_tanggungan' => 8,
                'no_npwp' => '89.090.028.5-522.000',
                'no_bpjs_tenaga_kerja' => '17003052663',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1979-05-01')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1979-05-01')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-008168-53-3'
            ],
            [
                'id_user' => 26,
                // 'nama' => 'Albert Hadith Pramono',
                'nik' => '1081044C',
                'id_kota_kerja' => 96,
                'id_unit' => 2,
                'id_level_karyawan' => 6,
                'status_tanggungan' => 7,
                'no_npwp' => '77.093.850.4-502.000',
                'no_bpjs_tenaga_kerja' => '05L20076077',
                'no_bpjs_kesehatan' => '0002234363905',
                'tanggal_masuk' => '2010-03-01',
                'tanggal_pensiun' => Carbon::parse('1981-11-06')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1981-11-06')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032758 50 4'
            ],
            [
                'id_user' => 27,
                // 'nama' => 'Adil Sanjaya',
                'nik' => '1681066C',
                'id_kota_kerja' => 96,
                'id_unit' => 4,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 8,
                'no_npwp' => '68.357.062.6-603.000',
                'no_bpjs_tenaga_kerja' => '17003052739',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1981-11-15')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1981-11-15')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-037692-50-9'
            ],
            [
                'id_user' => 28,
                // 'nama' => 'Desye Miftakhul Ikhwan',
                'nik' => '1678068C',
                'id_kota_kerja' => 96,
                'id_unit' => 4,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 8,
                'no_npwp' => '68.357.056.8-648.000',
                'no_bpjs_tenaga_kerja' => '17003052689',
                'no_bpjs_kesehatan' => '0002354908983',
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1978-12-16')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1978-12-16')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-037694-50-1'
            ],
            [
                'id_user' => 29,
                // 'nama' => 'Moh. Fathoni Arief',
                'nik' => '1681071C',
                'id_kota_kerja' => 96,
                'id_unit' => 2,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 6,
                'no_npwp' => '68.357.024.6-522.000',
                'no_bpjs_tenaga_kerja' => '17003052697',
                'no_bpjs_kesehatan' => '0002354908746',
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1981-04-11')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1981-04-11')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-037687-50-4'
            ],
            [
                'id_user' => 30,
                // 'nama' => 'Rahan Sukma Yudha',
                'nik' => '1685076C',
                'id_kota_kerja' => 96,
                'id_unit' => 2,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 6,
                'no_npwp' => '68.357.052.7.517.000',
                'no_bpjs_tenaga_kerja' => '17003052721',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1985-08-13')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1985-08-13')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-037689-50-6'
            ],
            [
                'id_user' => 31,
                // 'nama' => 'Heri Siswoyo',
                'nik' => '1781095C',
                'id_kota_kerja' => 96,
                'id_unit' => 2,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 8,
                'no_npwp' => '68.357.049.3-647.000',
                'no_bpjs_tenaga_kerja' => '18000974131',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2017-09-01',
                'tanggal_pensiun' => Carbon::parse('1981-12-25')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1981-12-25')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-056823-50-1'
            ],
            [
                'id_user' => 32,
                // 'nama' => 'Imam Pujianto',
                'nik' => '1780096C',
                'id_kota_kerja' => 96,
                'id_unit' => 4,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 7,
                'no_npwp' => '25.699.014.4-652.000',
                'no_bpjs_tenaga_kerja' => '17059717631',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2017-08-01',
                'tanggal_pensiun' => Carbon::parse('1980-10-31')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1980-10-31')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-056307-50-5'
            ],
            [
                'id_user' => 33,
                // 'nama' => 'Meliawan Panuwun Budi Sumaton',
                'nik' => '1679070C',
                'id_kota_kerja' => 96,
                'id_unit' => 2,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 7,
                'no_npwp' => '68.357.024.6-522.000',
                'no_bpjs_tenaga_kerja' => '17003052622',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1979-04-03')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1979-04-03')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-039549-50-8'
            ],
            [
                'id_user' => 34,
                // 'nama' => 'Dwi Cahyono',
                'nik' => '1682077C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 3,
                'status_tanggungan' => 7,
                'no_npwp' => '79.975.167.2-522.000',
                'no_bpjs_tenaga_kerja' => '17003052747',
                'no_bpjs_kesehatan' => '0002354909073',
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1982-02-26')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1982-02-26')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-033635-50-5'
            ],
            [
                'id_user' => 35,
                // 'nama' => 'Rezka Dwima Kusumaharja',
                'nik' => '1893112C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '84.174.321.4-426.000',
                'no_bpjs_tenaga_kerja' => '19004843629',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2018-10-01',
                'tanggal_pensiun' => Carbon::parse('1993-04-26')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1993-04-26')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '1078-01-054564-50-7'
            ],
            [
                'id_user' => 36,
                // 'nama' => 'Hanaf Ashari',
                'nik' => '1889104C',
                'id_kota_kerja' => 96,
                'id_unit' => 4,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '66.843.485.5-541.000',
                'no_bpjs_tenaga_kerja' => '15052037874',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2018-08-01',
                'tanggal_pensiun' => Carbon::parse('1989-11-20')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1989-11-20')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '7809-01-000240-53-2'
            ],
            [
                'id_user' => 37,
                // 'nama' => 'Prima Harsha Ade Septiawan',
                'nik' => '1890105C',
                'id_kota_kerja' => 96,
                'id_unit' => 3,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 5,
                'no_npwp' => '87.618.260.1-521.000',
                'no_bpjs_tenaga_kerja' => '16055158279',
                'no_bpjs_kesehatan' => '0001620658629',
                'tanggal_masuk' => '2018-08-01',
                'tanggal_pensiun' => Carbon::parse('1990-09-01')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1990-09-01')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '3110-01-041165-53-6'
            ],
            [
                'id_user' => 38,
                // 'nama' => 'Wisnu Enggar Suprapto',
                'nik' => '1890107C',
                'id_kota_kerja' => 96,
                'id_unit' => 4,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '73.003.992.2-521.000',
                'no_bpjs_tenaga_kerja' => '14007210470',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2018-08-01',
                'tanggal_pensiun' => Carbon::parse('1990-06-19')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1990-06-19')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '3110-01-041163-53-4'
            ],
            [
                'id_user' => 39,
                // 'nama' => 'B. Koen Agus Bondan Cahyono',
                'nik' => '1078039C',
                'id_kota_kerja' => 96,
                'id_unit' => 3,
                'id_level_karyawan' => 8,
                'status_tanggungan' => 7,
                'no_npwp' => '68.357.035.2-522.000',
                'no_bpjs_tenaga_kerja' => '05L20076473',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2010-03-01',
                'tanggal_pensiun' => Carbon::parse('1978-08-22')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1978-08-22')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032751 50 2 '
            ],
            [
                'id_user' => 40,
                // 'nama' => 'Anton Priyanto',
                'nik' => '1082041C',
                'id_kota_kerja' => 96,
                'id_unit' => 3,
                'id_level_karyawan' => 6,
                'status_tanggungan' => 8,
                'no_npwp' => '68.357.042.8-522.000',
                'no_bpjs_tenaga_kerja' => '05L20076291',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2010-03-01',
                'tanggal_pensiun' => Carbon::parse('1982-06-03')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1982-06-03')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032745 50 1'
            ],
            [
                'id_user' => 41,
                // 'nama' => 'Irboni Utami',
                'nik' => '1682069C',
                'id_kota_kerja' => 96,
                'id_unit' => 3,
                'id_level_karyawan' => 6,
                'status_tanggungan' => 7,
                'no_npwp' => '68.357.039.4-621.000',
                'no_bpjs_tenaga_kerja' => '17003052713',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1982-03-03')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1982-03-03')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-037695-50-7'
            ],
            [
                'id_user' => 42,
                // 'nama' => 'Rudy Haryanto',
                'nik' => '1681073C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 6,
                'no_npwp' => '68.357.027.9-629-000',
                'no_bpjs_tenaga_kerja' => '17003052796',
                'no_bpjs_kesehatan' => '0002358494673',
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1981-03-24')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1981-03-24')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-037688-50-0'
            ],
            [
                'id_user' => 43,
                // 'nama' => 'Widyo Agung Prabowo',
                'nik' => '1782087C',
                'id_kota_kerja' => 96,
                'id_unit' => 3,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 7,
                'no_npwp' => '97.428.040.6-522.000',
                'no_bpjs_tenaga_kerja' => '08019061012',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2017-07-03',
                'tanggal_pensiun' => Carbon::parse('1982-10-22')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1982-10-22')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 033637 50 7'
            ],
            [
                'id_user' => 44,
                // 'nama' => 'Tri Hendro Wahyono',
                'nik' => '1679075C',
                'id_kota_kerja' => 96,
                'id_unit' => 2,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 8,
                'no_npwp' => '49.637.676.5-401.000',
                'no_bpjs_tenaga_kerja' => '17003052671',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1979-01-15')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1979-01-15')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-037691-50-3'
            ],
            [
                'id_user' => 45,
                // 'nama' => 'Joko Pratomo',
                'nik' => '1681078C',
                'id_kota_kerja' => 96,
                'id_unit' => 3,
                'id_level_karyawan' => 3,
                'status_tanggungan' => 8,
                'no_npwp' => '97.428.035.6-623.000',
                'no_bpjs_tenaga_kerja' => '17003052788',
                'no_bpjs_kesehatan' => '0002354908948',
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1981-11-06')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1981-11-06')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-037693-50-5'
            ],
            [
                'id_user' => 46,
                // 'nama' => 'Muhammad Isnain Wiyasatama',
                'nik' => '1783094C',
                'id_kota_kerja' => 96,
                'id_unit' => 3,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 7,
                'no_npwp' => '79.975.192.0-532.000',
                'no_bpjs_tenaga_kerja' => '07005251660',
                'no_bpjs_kesehatan' => '0001703153946',
                'tanggal_masuk' => '2017-08-01',
                'tanggal_pensiun' => Carbon::parse('1983-01-15')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1983-01-15')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-056308-50-1'
            ],
            [
                'id_user' => 47,
                // 'nama' => 'Kartika Agus Candra',
                'nik' => '1778089C',
                'id_kota_kerja' => 96,
                'id_unit' => 3,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 6,
                'no_npwp' => '26.788.310.6-652.000',
                'no_bpjs_tenaga_kerja' => '17054862309',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2017-07-03',
                'tanggal_pensiun' => Carbon::parse('1978-08-17')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1978-08-17')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '6682 01 000650 50 2'
            ],
            [
                'id_user' => 48,
                // 'nama' => 'Eko Ariyanto',
                'nik' => '1587065C',
                'id_kota_kerja' => 96,
                'id_unit' => 3,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 7,
                'no_npwp' => '57.311.374.3-543.000',
                'no_bpjs_tenaga_kerja' => '07L20007953',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2015-05-01',
                'tanggal_pensiun' => Carbon::parse('1987-04-27')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1987-04-27')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 033651 50 1'
            ],
            [
                'id_user' => 49,
                // 'nama' => 'Dhito Fasagi Nugroho',
                'nik' => '1892103C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '76.919.013.3-522.000',
                'no_bpjs_tenaga_kerja' => '16055158303',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2018-08-01',
                'tanggal_pensiun' => Carbon::parse('1992-05-02')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1992-05-02')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-039396-50-7'
            ],
            [
                'id_user' => 50,
                // 'nama' => 'Muhammad Hari Wibowo',
                'nik' => '1782093C',
                'id_kota_kerja' => 96,
                'id_unit' => 3,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 7,
                'no_npwp' => '68.357.031.1-657.000',
                'no_bpjs_tenaga_kerja' => '17059717623',
                'no_bpjs_kesehatan' => '0001815703244',
                'tanggal_masuk' => '2017-08-01',
                'tanggal_pensiun' => Carbon::parse('1982-01-08')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1982-01-08')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-056309-50-7'
            ],
            [
                'id_user' => 51,
                // 'nama' => 'Brilian Karisma',
                'nik' => '1891102C',
                'id_kota_kerja' => 96,
                'id_unit' => 2,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 5,
                'no_npwp' => '54.245.590.2-522.000',
                'no_bpjs_tenaga_kerja' => '16055158287',
                'no_bpjs_kesehatan' => '0000080950059',
                'tanggal_masuk' => '2018-08-01',
                'tanggal_pensiun' => Carbon::parse('1991-07-30')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1991-07-30')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '3121-01-021061-53-9'
            ],
            [
                'id_user' => 52,
                // 'nama' => 'Septian Helmi Putra',
                'nik' => '1893106C',
                'id_kota_kerja' => 96,
                'id_unit' => 4,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '73.544.396.2-522.000',
                'no_bpjs_tenaga_kerja' => '16055158329',
                'no_bpjs_kesehatan' => '0000080780657',
                'tanggal_masuk' => '2018-08-01',
                'tanggal_pensiun' => Carbon::parse('1993-09-12')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1993-09-12')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '6680-01-001056-50-9'
            ],
            [
                'id_user' => 53,
                // 'nama' => 'Agus Gunanto',
                'nik' => '1370055C',
                'id_kota_kerja' => 96,
                'id_unit' => 4,
                'id_level_karyawan' => 8,
                'status_tanggungan' => 8,
                'no_npwp' => '07.887.590.3-642.000',
                'no_bpjs_tenaga_kerja' => NULL,
                'no_bpjs_kesehatan' => '0002354909038',
                'tanggal_masuk' => '2013-12-01',
                'tanggal_pensiun' => Carbon::parse('1970-10-09')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1970-10-09')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 034152 50 0'
            ],
            [
                'id_user' => 54,
                // 'nama' => 'Sunardi',
                'nik' => '1078040C',
                'id_kota_kerja' => 96,
                'id_unit' => 4,
                'id_level_karyawan' => 6,
                'status_tanggungan' => 8,
                'no_npwp' => '68.357.043.6-522.000',
                'no_bpjs_tenaga_kerja' => '10012290697',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2010-03-01',
                'tanggal_pensiun' => Carbon::parse('1978-06-05')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1978-06-05')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032759 50 0'
            ],
            [
                'id_user' => 55,
                // 'nama' => 'Pardi',
                'nik' => '1081042C',
                'id_kota_kerja' => 96,
                'id_unit' => 4,
                'id_level_karyawan' => 6,
                'status_tanggungan' => 7,
                'no_npwp' => '68.357.029.5-525.000',
                'no_bpjs_tenaga_kerja' => '05L20076465',
                'no_bpjs_kesehatan' => '0002354908825',
                'tanggal_masuk' => '2010-03-01',
                'tanggal_pensiun' => Carbon::parse('1981-11-09')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1981-11-09')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032760 50 1'
            ],
            [
                'id_user' => 56,
                // 'nama' => 'Reny Apriana',
                'nik' => '1992114C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '77.603.985.1-522.000',
                'no_bpjs_tenaga_kerja' => '14017137440',
                'no_bpjs_kesehatan' => '0001300739387',
                'tanggal_masuk' => '2019-07-01',
                'tanggal_pensiun' => Carbon::parse('1992-04-20')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1992-04-20')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '6680-01-000718-50-6'
            ],
            [
                'id_user' => 57,
                // 'nama' => 'Sigit Suwarto',
                'nik' => '1078038C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 8,
                'status_tanggungan' => 8,
                'no_npwp' => '68.357.058.4-522.000',
                'no_bpjs_tenaga_kerja' => '02L00184336',
                'no_bpjs_kesehatan' => '0002358494684',
                'tanggal_masuk' => '2010-03-01',
                'tanggal_pensiun' => Carbon::parse('1978-11-28')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1978-11-28')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032753 50 4'
            ],
            [
                'id_user' => 58,
                // 'nama' => 'A. Yusuf Rizal',
                'nik' => '1080037C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 8,
                'status_tanggungan' => 8,
                'no_npwp' => '68.357.037.8-501.000',
                'no_bpjs_tenaga_kerja' => '10012290705',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2010-03-01',
                'tanggal_pensiun' => Carbon::parse('1980-04-25')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1980-04-25')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032752 50 8'
            ],
            [
                'id_user' => 59,
                // 'nama' => 'Agus Sugiharto',
                'nik' => '0672025C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 8,
                'status_tanggungan' => 6,
                'no_npwp' => '59.737.109.5-522.000',
                'no_bpjs_tenaga_kerja' => '07001863229',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2006-12-01',
                'tanggal_pensiun' => Carbon::parse('1972-09-08')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1972-09-08')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032754 50 0'
            ],
            [
                'id_user' => 60,
                // 'nama' => 'Zam Zam Nurzaman',
                'nik' => '1084046C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 6,
                'status_tanggungan' => 6,
                'no_npwp' => '89.569.109.5-522.000',
                'no_bpjs_tenaga_kerja' => '10012290689',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2010-04-01',
                'tanggal_pensiun' => Carbon::parse('1984-04-24')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1984-04-24')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032748 50 9'
            ],
            [
                'id_user' => 61,
                // 'nama' => 'Herji Hasnanto',
                'nik' => '1884108C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 7,
                'no_npwp' => '58.988.047.5.528.000',
                'no_bpjs_tenaga_kerja' => '18095992576',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2018-08-01',
                'tanggal_pensiun' => Carbon::parse('1984-11-11')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1984-11-11')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-065135-50-5'
            ],
            [
                'id_user' => 62,
                // 'nama' => 'Tofik Budianto',
                'nik' => '1990113C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 6,
                'no_npwp' => '87.187.790.3-521.000',
                'no_bpjs_tenaga_kerja' => '17042745301',
                'no_bpjs_kesehatan' => '0001886105529',
                'tanggal_masuk' => '2019-07-01',
                'tanggal_pensiun' => Carbon::parse('1990-01-02')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1990-01-02')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '3110-01-035758-53-7'
            ],
            [
                'id_user' => 63,
                // 'nama' => 'Seghesti Damar Cahyono',
                'nik' => '1682074C',
                'id_kota_kerja' => 96,
                'id_unit' => 1,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 7,
                'no_npwp' => '68.357.060.0-644.000',
                'no_bpjs_tenaga_kerja' => '17003052754',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1982-01-01')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1982-01-01')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '3120-01-002313-50-7'
            ],
            [
                'id_user' => 64,
                // 'nama' => 'Ponidi Rahmanto',
                'nik' => '1682080C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 3,
                'status_tanggungan' => 7,
                'no_npwp' => '97.428.037.2-603.000',
                'no_bpjs_tenaga_kerja' => '17003052770',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1982-03-26')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1982-03-26')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-033596-50-7'
            ],
            [
                'id_user' => 65,
                // 'nama' => 'Rochman Nurhidayat',
                'nik' => '1778088C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 7,
                'no_npwp' => '97.428.039.8-522.000',
                'no_bpjs_tenaga_kerja' => '08019061038',
                'no_bpjs_kesehatan' => '0002358494662',
                'tanggal_masuk' => '2017-07-03',
                'tanggal_pensiun' => Carbon::parse('1978-11-26')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1978-11-26')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '3115 01 000732 53 2'
            ],
            [
                'id_user' => 66,
                // 'nama' => 'Lia Nopitarose',
                'nik' => '1186048C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 1,
                'no_npwp' => '36.836.479.0-514.000',
                'no_bpjs_tenaga_kerja' => '11038434483',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2011-07-01',
                'tanggal_pensiun' => Carbon::parse('1986-11-14')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1986-11-14')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032749 50 5'
            ],
            [
                'id_user' => 67,
                // 'nama' => 'Sarjoko',
                'nik' => '1790092C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '74.636.030.4-543.000',
                'no_bpjs_tenaga_kerja' => '17054862358',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2017-07-03',
                'tanggal_pensiun' => Carbon::parse('1990-07-18')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1990-07-18')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '6632 01 011384 53 9'
            ],
            [
                'id_user' => 68,
                // 'nama' => 'Suhermanto',
                'nik' => '1756085C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 7,
                'status_tanggungan' => 5,
                'no_npwp' => '57.311.375.0-543.000',
                'no_bpjs_tenaga_kerja' => NULL,
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2017-02-01',
                'tanggal_pensiun' => Carbon::parse('1956-06-29')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1956-06-29')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-040216-50-4'
            ],
            [
                'id_user' => 69,
                // 'nama' => 'Pratama Mukti',
                'nik' => '0577017J',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 7,
                'no_npwp' => '24.706.968.5-429.000',
                'no_bpjs_tenaga_kerja' => '05JD0025958',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2005-04-01',
                'tanggal_pensiun' => Carbon::parse('1977-08-29')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1977-08-29')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01 070259 50 4'
            ],
            [
                'id_user' => 70,
                // 'nama' => 'Hadi Susilo Purwoko',
                'nik' => '0577019C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 8,
                'no_npwp' => '59.737.107.9-522.000',
                'no_bpjs_tenaga_kerja' => '7,001,863,245',
                'no_bpjs_kesehatan' => '0002354908869',
                'tanggal_masuk' => '2005-08-01',
                'tanggal_pensiun' => Carbon::parse('1977-05-25')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1977-05-25')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032761 50 7'
            ],
            [
                'id_user' => 71,
                // 'nama' => 'Nur Efendi',
                'nik' => '1682079C',
                'id_kota_kerja' => 96,
                'id_unit' => 2,
                'id_level_karyawan' => 3,
                'status_tanggungan' => 6,
                'no_npwp' => '25.225.967.6-657.000',
                'no_bpjs_tenaga_kerja' => '17003052762',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1982-10-29')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1982-10-29')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-037690-50-7'
            ],
            [
                'id_user' => 72,
                // 'nama' => 'Ageng Iriyanto',
                'nik' => '1780091C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 6,
                'no_npwp' => '07.893.730.7-653.000',
                'no_bpjs_tenaga_kerja' => '08019061046',
                'no_bpjs_kesehatan' => '0001906418057',
                'tanggal_masuk' => '2017-07-03',
                'tanggal_pensiun' => Carbon::parse('1980-03-15')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1980-03-15')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '3120 01 026032 53 1'
            ],
            [
                'id_user' => 73,
                // 'nama' => 'Erni Nurhaeni',
                'nik' => '1281052C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 1,
                'no_npwp' => '45.981.316.8-522.000',
                'no_bpjs_tenaga_kerja' => '07L20006898',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2012-07-01',
                'tanggal_pensiun' => Carbon::parse('1981-09-08')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1981-09-08')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032747 50 3'
            ],
            [
                'id_user' => 74,
                // 'nama' => 'Dah Shaaddin Kahar',
                'nik' => '0778030J',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 6,
                'status_tanggungan' => 8,
                'no_npwp' => '24.587.656.0-013.000',
                'no_bpjs_tenaga_kerja' => '05K50089678',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2007-08-01',
                'tanggal_pensiun' => Carbon::parse('1978-07-10')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1978-07-10')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032762 50 3'
            ],
            [
                'id_user' => 75,
                // 'nama' => 'Muhammad Huda',
                'nik' => '1479057C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 3,
                'no_npwp' => '48.918.219.6-524.000',
                'no_bpjs_tenaga_kerja' => '14,009,603,227',
                'no_bpjs_kesehatan' => '0002354908915',
                'tanggal_masuk' => '2014-03-01',
                'tanggal_pensiun' => Carbon::parse('1979-11-07')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1979-11-07')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 034134 50 2'
            ],
            [
                'id_user' => 76,
                // 'nama' => 'Cahyo Vebiyanto',
                'nik' => '1681067C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 8,
                'no_npwp' => '68.357.051.9-617.000',
                'no_bpjs_tenaga_kerja' => '17003052655',
                'no_bpjs_kesehatan' => '0002354908779',
                'tanggal_masuk' => '2016-02-01',
                'tanggal_pensiun' => Carbon::parse('1981-01-17')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1981-01-17')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0142-01-028937-50-2'
            ],
            [
                'id_user' => 77,
                // 'nama' => 'Febriana Eryanti',
                'nik' => '1890111C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '82.237.269.4-429.000',
                'no_bpjs_tenaga_kerja' => '19004843611',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2018-10-01',
                'tanggal_pensiun' => Carbon::parse('1990-02-04')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1990-02-04')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-051202-50-6'
            ],
            [
                'id_user' => 78,
                // 'nama' => 'Ibnu Hamin Thohari',
                'nik' => '1778090C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 8,
                'no_npwp' => '26.268.207.3-655.000',
                'no_bpjs_tenaga_kerja' => '17054862341',
                'no_bpjs_kesehatan' => '0002354908961',
                'tanggal_masuk' => '2017-07-03',
                'tanggal_pensiun' => Carbon::parse('1978-01-07')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1978-01-07')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 040283 50 1'
            ],
            [
                'id_user' => 79,
                // 'nama' => 'Suraji',
                'nik' => '1783084J',
                'id_kota_kerja' => 96,
                'id_unit' => 5,
                'id_level_karyawan' => 8,
                'status_tanggungan' => 7,
                'no_npwp' => '48.544.211.5-523.000',
                'no_bpjs_tenaga_kerja' => '18072156914',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2017-01-01',
                'tanggal_pensiun' => Carbon::parse('1983-11-02')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1983-11-02')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206-01-133321-50-9'
            ],
            [
                'id_user' => 80,
                // 'nama' => 'Sutikno',
                'nik' => '0752028C',
                'id_kota_kerja' => 96,
                'id_unit' => 5,
                'id_level_karyawan' => 7,
                'status_tanggungan' => 5,
                'no_npwp' => '07.322.675.5-047.000',
                'no_bpjs_tenaga_kerja' => NULL,
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2007-05-01',
                'tanggal_pensiun' => Carbon::parse('1952-02-15')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1952-02-15')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '2135 01 000202 56 0'
            ],
            [
                'id_user' => 81,
                // 'nama' => 'Bramanto Seno',
                'nik' => '1586063J',
                'id_kota_kerja' => 42,
                'id_unit' => 5,
                'id_level_karyawan' => 6,
                'status_tanggungan' => 7,
                'no_npwp' => '87.733.246.0-432.000',
                'no_bpjs_tenaga_kerja' => '11020964315',
                'no_bpjs_kesehatan' => '0001838844832',
                'tanggal_masuk' => '2015-03-01',
                'tanggal_pensiun' => Carbon::parse('1986-10-26')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1986-10-26')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01 108383 50 2'
            ],
            [
                'id_user' => 82,
                // 'nama' => 'Rosarina',
                'nik' => '1386053J',
                'id_kota_kerja' => 42,
                'id_unit' => 5,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 1,
                'no_npwp' => '89.947.561.0-036.000',
                'no_bpjs_tenaga_kerja' => '13007379814',
                'no_bpjs_kesehatan' => '0002234342327',
                'tanggal_masuk' => '2013-02-01',
                'tanggal_pensiun' => Carbon::parse('1986-05-18')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1986-05-18')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01070249 50 9'
            ],
            [
                'id_user' => 83,
                // 'nama' => 'Andi Burhan Nawawi',
                'nik' => '1070045C',
                'id_kota_kerja' => 96,
                'id_unit' => 5,
                'id_level_karyawan' => 6,
                'status_tanggungan' => 7,
                'no_npwp' => '68.357.023.8-805.000',
                'no_bpjs_tenaga_kerja' => '10012290671',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2010-04-01',
                'tanggal_pensiun' => Carbon::parse('1970-03-02')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1970-03-02')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032808 50 3'
            ],
            [
                'id_user' => 84,
                // 'nama' => 'Eko Heriyanto',
                'nik' => '1183050J',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 7,
                'no_npwp' => '57.311.374.3-543.000',
                'no_bpjs_tenaga_kerja' => '11032669803',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2011-10-01',
                'tanggal_pensiun' => Carbon::parse('1983-10-27')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1983-10-27')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0206 01070228 50 3'
            ],
            [
                'id_user' => 85,
                // 'nama' => 'Feri Surya Pranadi',
                'nik' => '0476011C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 6,
                'status_tanggungan' => 6,
                'no_npwp' => '59.737.108.7-522.000',
                'no_bpjs_tenaga_kerja' => '05JD0025966',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2004-05-01',
                'tanggal_pensiun' => Carbon::parse('1976-02-25')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1976-02-25')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032797 50 8'
            ],
            [
                'id_user' => 86,
                // 'nama' => 'Resti Widia Ningsih',
                'nik' => '1283051C',
                'id_kota_kerja' => 96,
                'id_unit' => 5,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 1,
                'no_npwp' => '44.976.787.0-421.000',
                'no_bpjs_tenaga_kerja' => '12003830549',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2012-02-01',
                'tanggal_pensiun' => Carbon::parse('1983-10-06')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1983-10-06')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032750 50 6'
            ],
            [
                'id_user' => 87,
                // 'nama' => 'Arif Uji Ristiyanto',
                'nik' => '1786097C',
                'id_kota_kerja' => 96,
                'id_unit' => 5,
                'id_level_karyawan' => 4,
                'status_tanggungan' => 5,
                'no_npwp' => '67.302.367.7-521.000',
                'no_bpjs_tenaga_kerja' => '11000317351',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2017-08-01',
                'tanggal_pensiun' => Carbon::parse('1986-07-23')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1986-07-23')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-056310-50-8'
            ],
            [
                'id_user' => 88,
                // 'nama' => 'Suko Cahyo Hantoko',
                'nik' => '1177049C',
                'id_kota_kerja' => 96,
                'id_unit' => 5,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 7,
                'no_npwp' => '77.671.811.6-517.000',
                'no_bpjs_tenaga_kerja' => '11038434509',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2011-07-01',
                'tanggal_pensiun' => Carbon::parse('1977-11-02')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1977-11-02')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106 01 032757 50 8'
            ],
            [
                'id_user' => 89,
                // 'nama' => 'Wasiyat Rohmat Pamuji',
                'nik' => '1777086C',
                'id_kota_kerja' => 96,
                'id_unit' => 4,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 7,
                'no_npwp' => '47.030.270.4-522.000',
                'no_bpjs_tenaga_kerja' => '11034091873',
                'no_bpjs_kesehatan' => '0000075799203',
                'tanggal_masuk' => '2017-07-03',
                'tanggal_pensiun' => Carbon::parse('1977-01-17')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1977-01-17')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '3115 01 000733 53 8'
            ],
            [
                'id_user' => 90,
                // 'nama' => 'Atmaji Rahmat Wisesho',
                'nik' => '1889098C',
                'id_kota_kerja' => 96,
                'id_unit' => 5,
                'id_level_karyawan' => 2,
                'status_tanggungan' => 6,
                'no_npwp' => '55.017.911.3-412.000',
                'no_bpjs_tenaga_kerja' => '18065800809',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2018-04-23',
                'tanggal_pensiun' => Carbon::parse('1989-12-08')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1989-12-08')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-064187-50-9'
            ],
            [
                'id_user' => 91,
                // 'nama' => 'Defza Huristu',
                'nik' => '1894110C',
                'id_kota_kerja' => 96,
                'id_unit' => 5,
                'id_level_karyawan' => 3,
                'status_tanggungan' => 1,
                'no_npwp' => '86.797.279.6-204.000',
                'no_bpjs_tenaga_kerja' => '19004843603',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2018-08-06',
                'tanggal_pensiun' => Carbon::parse('1994-01-29')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1994-01-29')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-065187-50-2'
            ],
            [
                'id_user' => 92,
                // 'nama' => 'Lifransyah Gumay',
                'nik' => '2JA100001',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 10,
                'status_tanggungan' => 5,
                'no_npwp' => NULL,
                'no_bpjs_tenaga_kerja' => NULL,
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => NULL,
                'tanggal_pensiun' => NULL,
                'sisa_masa_kerja' => NULL,
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '1150 01 000174 56 2'
            ],
            [
                'id_user' => 93,
                // 'nama' => 'Harry Satria',
                'nik' => '1E0000001',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 10,
                'status_tanggungan' => 6,
                'no_npwp' => NULL,
                'no_bpjs_tenaga_kerja' => NULL,
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => NULL,
                'tanggal_pensiun' => Carbon::parse('1954-10-24')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1954-10-24')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 1,
                'no_bank_payroll' => '126-0005979272'
            ],
            [
                'id_user' => 94,
                // 'nama' => 'Audrey Cecilia',
                'nik' => '2095117J',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '95.298.644.6-008.000',
                'no_bpjs_tenaga_kerja' => '20040184036',
                'no_bpjs_kesehatan' => '1156283583',
                'tanggal_masuk' => '2020-05-12',
                'tanggal_pensiun' => Carbon::parse('1995-09-19')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1995-09-19')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0929-01-015969-53-2'
            ],
            [
                'id_user' => 95,
                // 'nama' => 'Maria Friska',
                'nik' => '5JA2111112',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => NULL,
                'no_bpjs_tenaga_kerja' => NULL,
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2020-01-06',
                'tanggal_pensiun' => NULL,
                'sisa_masa_kerja' => NULL,
                'id_bank_payroll' => NULL,
                'no_bank_payroll' => NULL
            ],
            [
                'id_user' => 96,
                // 'nama' => 'Nabilah Syah Putri',
                'nik' => '5JA2111111',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => NULL,
                'no_bpjs_tenaga_kerja' => NULL,
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => NULL,
                'tanggal_pensiun' => NULL,
                'sisa_masa_kerja' => NULL,
                'id_bank_payroll' => NULL,
                'no_bank_payroll' => NULL
            ],
            [
                'id_user' => 97,
                // 'nama' => 'Ichvania Annisa Marantika',
                'nik' => '1992115C',
                'id_kota_kerja' => 96,
                'id_unit' => 5,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '73.338.377.2-629.000',
                'no_bpjs_tenaga_kerja' => '14036006980',
                'no_bpjs_kesehatan' => '0001785233452',
                'tanggal_masuk' => '2019-12-01',
                'tanggal_pensiun' => Carbon::parse('1992-09-13')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1992-09-13')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '3118-01-030142-53-9'
            ],
            [
                'id_user' => 98,
                // 'nama' => 'Gian Djohan Junior',
                'nik' => '2096116C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '3171070204960000',
                'no_bpjs_tenaga_kerja' => '20028725370',
                'no_bpjs_kesehatan' => '0001624959066',
                'tanggal_masuk' => '2020-01-06',
                'tanggal_pensiun' => Carbon::parse('1996-04-02')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1996-04-02')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-081143-50-2'
            ],
            [
                'id_user' => 99,
                // 'nama' => 'Catur Yulianto',
                'nik' => '2072118C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 6,
                'status_tanggungan' => 6,
                'no_npwp' => '08.754.857.4-625.000',
                'no_bpjs_tenaga_kerja' => '16041634292',
                'no_bpjs_kesehatan' => '0002159920078',
                'tanggal_masuk' => '2020-07-01',
                'tanggal_pensiun' => Carbon::parse('1972-07-20')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1972-07-20')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0409-01-007429-50-0'
            ],
            [
                'id_user' => 100,
                // 'nama' => 'Joko Firmanto',
                'nik' => '2093119C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 6,
                'no_npwp' => '73.983.488.5-321.000',
                'no_bpjs_tenaga_kerja' => '19039315114',
                'no_bpjs_kesehatan' => '0002158818952',
                'tanggal_masuk' => '2020-07-01',
                'tanggal_pensiun' => Carbon::parse('1993-03-11')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1993-03-11')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-085027-50-4'
            ],
            [
                'id_user' => 101,
                // 'nama' => 'Dimas Darma Setyawan',
                'nik' => '2092120C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '80.386.319.0-522.000',
                'no_bpjs_tenaga_kerja' => '19039313614',
                'no_bpjs_kesehatan' => '0002253189104',
                'tanggal_masuk' => '2020-07-01',
                'tanggal_pensiun' => Carbon::parse('1992-10-15')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1992-10-15')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0106-01-085026-50-8'
            ],
            [
                'id_user' => 102,
                // 'nama' => 'Mirza Lutfi',
                'nik' => '2094121C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 1,
                'no_npwp' => '75.856.574.1-522.000',
                'no_bpjs_tenaga_kerja' => '19039313747',
                'no_bpjs_kesehatan' => '0001079472216',
                'tanggal_masuk' => '2020-07-01',
                'tanggal_pensiun' => Carbon::parse('1994-06-10')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1994-06-10')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '0026-01-095377-50-7'
            ],
            [
                'id_user' => 103,
                // 'nama' => 'Daryono',
                'nik' => '1882109C',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 1,
                'status_tanggungan' => 8,
                'no_npwp' => '54.209.127.7-522.000',
                'no_bpjs_tenaga_kerja' => '15058079359',
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => '2018-08-01',
                'tanggal_pensiun' => Carbon::parse('1982-05-03')->addYears(USIA_PENSIUN)->format('Y-m-d'),
                'sisa_masa_kerja' => Carbon::parse('1982-05-03')->addYears(USIA_PENSIUN)->diffInYears(Carbon::today()),
                'id_bank_payroll' => 5,
                'no_bank_payroll' => '6830-01-009712-53-2'
            ],
            [
                'id_user' => 104,
                // 'nama' => 'Wulan',
                'nik' => '6CP115111',
                'id_kota_kerja' => 96,
                'id_unit' => 5,
                'id_level_karyawan' => 1,
                'status_tanggungan' => NULL,
                'no_npwp' => NULL,
                'no_bpjs_tenaga_kerja' => NULL,
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => NULL,
                'tanggal_pensiun' => NULL,
                'sisa_masa_kerja' => NULL,
                'id_bank_payroll' => NULL,
                'no_bank_payroll' => NULL
            ],
            [
                'id_user' => 105,
                // 'nama' => 'Prita Purwanti',
                'nik' => '3CG117171',
                'id_kota_kerja' => 96,
                'id_unit' => 6,
                'id_level_karyawan' => 1,
                'status_tanggungan' => NULL,
                'no_npwp' => NULL,
                'no_bpjs_tenaga_kerja' => NULL,
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => NULL,
                'tanggal_pensiun' => NULL,
                'sisa_masa_kerja' => NULL,
                'id_bank_payroll' => NULL,
                'no_bank_payroll' => NULL
            ],
            [
                'id_user' => 106,
                // 'nama' => 'Krisdina Yulianto',
                'nik' => '2JA711111',
                'id_kota_kerja' => 42,
                'id_unit' => 1,
                'id_level_karyawan' => 1,
                'status_tanggungan' => NULL,
                'no_npwp' => NULL,
                'no_bpjs_tenaga_kerja' => NULL,
                'no_bpjs_kesehatan' => NULL,
                'tanggal_masuk' => NULL,
                'tanggal_pensiun' => NULL,
                'sisa_masa_kerja' => NULL,
                'id_bank_payroll' => NULL,
                'no_bank_payroll' => NULL
            ],
        ]);
    }
}
