<?php

use Illuminate\Database\Seeder;

class SeederTabelNegara extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::connection('master_sys')->statement("TRUNCATE TABLE ONLY sys.negara RESTART IDENTITY CASCADE");
        DB::connection('master_sys')->table('negara')->insert([
            [ 'nama' => 'Afghanistan', 'kode_telepon' => '93' ],
            [ 'nama' => 'Albania', 'kode_telepon' => '355' ],
            [ 'nama' => 'Algeria', 'kode_telepon' => '213' ],
            [ 'nama' => 'American Samoa', 'kode_telepon' => '1684' ],
            [ 'nama' => 'Andorra', 'kode_telepon' => '376' ],
            [ 'nama' => 'Angola', 'kode_telepon' => '244' ],
            [ 'nama' => 'Anguilla', 'kode_telepon' => '1264' ],
            [ 'nama' => 'Antarctica', 'kode_telepon' => '672' ],
            [ 'nama' => 'Antigua & Barbuda', 'kode_telepon' => '1268' ],
            [ 'nama' => 'Argentina', 'kode_telepon' => '54' ],
            [ 'nama' => 'Armenia', 'kode_telepon' => '374' ],
            [ 'nama' => 'Aruba', 'kode_telepon' => '297' ],
            [ 'nama' => 'Australia', 'kode_telepon' => '61' ],
            [ 'nama' => 'Austria', 'kode_telepon' => '43' ],
            [ 'nama' => 'Azerbaijan', 'kode_telepon' => '994' ],
            [ 'nama' => 'Bahamas', 'kode_telepon' => '1242' ],
            [ 'nama' => 'Bahrain', 'kode_telepon' => '973' ],
            [ 'nama' => 'Bangladesh', 'kode_telepon' => '880' ],
            [ 'nama' => 'Barbados', 'kode_telepon' => '1246' ],
            [ 'nama' => 'Belarus', 'kode_telepon' => '375' ],
            [ 'nama' => 'Belgium', 'kode_telepon' => '32' ],
            [ 'nama' => 'Belize', 'kode_telepon' => '501' ],
            [ 'nama' => 'Benin', 'kode_telepon' => '229' ],
            [ 'nama' => 'Bermuda', 'kode_telepon' => '1441' ],
            [ 'nama' => 'Bhutan', 'kode_telepon' => '975' ],
            [ 'nama' => 'Bolivia', 'kode_telepon' => '591' ],
            [ 'nama' => 'Bosnia', 'kode_telepon' => '387' ],
            [ 'nama' => 'Botswana', 'kode_telepon' => '267' ],
            [ 'nama' => 'Bouvet Island', 'kode_telepon' => '47' ],
            [ 'nama' => 'Brazil', 'kode_telepon' => '55' ],
            [ 'nama' => 'British Indian Ocean Territory', 'kode_telepon' => '246' ],
            [ 'nama' => 'British Virgin Islands', 'kode_telepon' => '1284' ],
            [ 'nama' => 'Brunei', 'kode_telepon' => '673' ],
            [ 'nama' => 'Bulgaria', 'kode_telepon' => '359' ],
            [ 'nama' => 'Burkina Faso', 'kode_telepon' => '226' ],
            [ 'nama' => 'Burundi', 'kode_telepon' => '257' ],
            [ 'nama' => 'Cambodia', 'kode_telepon' => '855' ],
            [ 'nama' => 'Cameroon', 'kode_telepon' => '237' ],
            [ 'nama' => 'Canada', 'kode_telepon' => '1' ],
            [ 'nama' => 'Cape Verde', 'kode_telepon' => '238' ],
            [ 'nama' => 'Caribbean Netherlands', 'kode_telepon' => '599' ],
            [ 'nama' => 'Cayman Islands', 'kode_telepon' => '1345' ],
            [ 'nama' => 'Central African Republic', 'kode_telepon' => '236' ],
            [ 'nama' => 'Chad', 'kode_telepon' => '235' ],
            [ 'nama' => 'Chile', 'kode_telepon' => '56' ],
            [ 'nama' => 'China', 'kode_telepon' => '86' ],
            [ 'nama' => 'Christmas Island', 'kode_telepon' => '61' ],
            [ 'nama' => 'Cocos (Keeling) Islands', 'kode_telepon' => '61' ],
            [ 'nama' => 'Colombia', 'kode_telepon' => '57' ],
            [ 'nama' => 'Comoros', 'kode_telepon' => '269' ],
            [ 'nama' => 'Congo - Brazzaville', 'kode_telepon' => '242' ],
            [ 'nama' => 'Congo - Kinshasa', 'kode_telepon' => '243' ],
            [ 'nama' => 'Cook Islands', 'kode_telepon' => '682' ],
            [ 'nama' => 'Costa Rica', 'kode_telepon' => '506' ],
            [ 'nama' => 'Croatia', 'kode_telepon' => '385' ],
            [ 'nama' => 'Cuba', 'kode_telepon' => '53' ],
            [ 'nama' => 'Curacao', 'kode_telepon' => '599' ],
            [ 'nama' => 'Cyprus', 'kode_telepon' => '357' ],
            [ 'nama' => 'Czech Republic', 'kode_telepon' => '420' ],
            [ 'nama' => 'Cote de Ivoire', 'kode_telepon' => '225' ],
            [ 'nama' => 'Denmark', 'kode_telepon' => '45' ],
            [ 'nama' => 'Djibouti', 'kode_telepon' => '253' ],
            [ 'nama' => 'Dominica', 'kode_telepon' => '1767' ],
            [ 'nama' => 'Dominican Republic', 'kode_telepon' => '1809' ],
            [ 'nama' => 'Dominican Republic', 'kode_telepon' => '1829' ],
            [ 'nama' => 'Dominican Republic', 'kode_telepon' => '1849' ],
            [ 'nama' => 'Ecuador', 'kode_telepon' => '593' ],
            [ 'nama' => 'Egypt', 'kode_telepon' => '20' ],
            [ 'nama' => 'El Salvador', 'kode_telepon' => '503' ],
            [ 'nama' => 'Equatorial Guinea', 'kode_telepon' => '240' ],
            [ 'nama' => 'Eritrea', 'kode_telepon' => '291' ],
            [ 'nama' => 'Estonia', 'kode_telepon' => '372' ],
            [ 'nama' => 'Ethiopia', 'kode_telepon' => '251' ],
            [ 'nama' => 'Falkland Islands', 'kode_telepon' => '500' ],
            [ 'nama' => 'Faroe Islands', 'kode_telepon' => '298' ],
            [ 'nama' => 'Fiji', 'kode_telepon' => '679' ],
            [ 'nama' => 'Finland', 'kode_telepon' => '358' ],
            [ 'nama' => 'France', 'kode_telepon' => '33' ],
            [ 'nama' => 'French Guiana', 'kode_telepon' => '594' ],
            [ 'nama' => 'French Polynesia', 'kode_telepon' => '689' ],
            [ 'nama' => 'French Southern Territories', 'kode_telepon' => '262' ],
            [ 'nama' => 'Gabon', 'kode_telepon' => '241' ],
            [ 'nama' => 'Gambia', 'kode_telepon' => '220' ],
            [ 'nama' => 'Georgia', 'kode_telepon' => '995' ],
            [ 'nama' => 'Germany', 'kode_telepon' => '49' ],
            [ 'nama' => 'Ghana', 'kode_telepon' => '233' ],
            [ 'nama' => 'Gibraltar', 'kode_telepon' => '350' ],
            [ 'nama' => 'Greece', 'kode_telepon' => '30' ],
            [ 'nama' => 'Greenland', 'kode_telepon' => '299' ],
            [ 'nama' => 'Grenada', 'kode_telepon' => '1473' ],
            [ 'nama' => 'Guadeloupe', 'kode_telepon' => '590' ],
            [ 'nama' => 'Guam', 'kode_telepon' => '1671' ],
            [ 'nama' => 'Guatemala', 'kode_telepon' => '502' ],
            [ 'nama' => 'Guernsey', 'kode_telepon' => '44' ],
            [ 'nama' => 'Guinea', 'kode_telepon' => '224' ],
            [ 'nama' => 'Guinea-Bissau', 'kode_telepon' => '245' ],
            [ 'nama' => 'Guyana', 'kode_telepon' => '592' ],
            [ 'nama' => 'Haiti', 'kode_telepon' => '509' ],
            [ 'nama' => 'Heard & McDonald Islands', 'kode_telepon' => '672' ],
            [ 'nama' => 'Honduras', 'kode_telepon' => '504' ],
            [ 'nama' => 'Hong Kong', 'kode_telepon' => '852' ],
            [ 'nama' => 'Hungary', 'kode_telepon' => '36' ],
            [ 'nama' => 'Iceland', 'kode_telepon' => '354' ],
            [ 'nama' => 'India', 'kode_telepon' => '91' ],
            [ 'nama' => 'Indonesia', 'kode_telepon' => '62' ],
            [ 'nama' => 'Iran', 'kode_telepon' => '98' ],
            [ 'nama' => 'Iraq', 'kode_telepon' => '964' ],
            [ 'nama' => 'Ireland', 'kode_telepon' => '353' ],
            [ 'nama' => 'Isle of Man', 'kode_telepon' => '44' ],
            [ 'nama' => 'Israel', 'kode_telepon' => '972' ],
            [ 'nama' => 'Italy', 'kode_telepon' => '39' ],
            [ 'nama' => 'Jamaica', 'kode_telepon' => '1876' ],
            [ 'nama' => 'Japan', 'kode_telepon' => '81' ],
            [ 'nama' => 'Jersey', 'kode_telepon' => '44' ],
            [ 'nama' => 'Jordan', 'kode_telepon' => '962' ],
            [ 'nama' => 'Kazakhstan', 'kode_telepon' => '7' ],
            [ 'nama' => 'Kenya', 'kode_telepon' => '254' ],
            [ 'nama' => 'Kiribati', 'kode_telepon' => '686' ],
            [ 'nama' => 'Kuwait', 'kode_telepon' => '965' ],
            [ 'nama' => 'Kyrgyzstan', 'kode_telepon' => '996' ],
            [ 'nama' => 'Laos', 'kode_telepon' => '856' ],
            [ 'nama' => 'Latvia', 'kode_telepon' => '371' ],
            [ 'nama' => 'Lebanon', 'kode_telepon' => '961' ],
            [ 'nama' => 'Lesotho', 'kode_telepon' => '266' ],
            [ 'nama' => 'Liberia', 'kode_telepon' => '231' ],
            [ 'nama' => 'Libya', 'kode_telepon' => '218' ],
            [ 'nama' => 'Liechtenstein', 'kode_telepon' => '423' ],
            [ 'nama' => 'Lithuania', 'kode_telepon' => '370' ],
            [ 'nama' => 'Luxembourg', 'kode_telepon' => '352' ],
            [ 'nama' => 'Macau', 'kode_telepon' => '853' ],
            [ 'nama' => 'Macedonia', 'kode_telepon' => '389' ],
            [ 'nama' => 'Madagascar', 'kode_telepon' => '261' ],
            [ 'nama' => 'Malawi', 'kode_telepon' => '265' ],
            [ 'nama' => 'Malaysia', 'kode_telepon' => '60' ],
            [ 'nama' => 'Maldives', 'kode_telepon' => '960' ],
            [ 'nama' => 'Mali', 'kode_telepon' => '223' ],
            [ 'nama' => 'Malta', 'kode_telepon' => '356' ],
            [ 'nama' => 'Marshall Islands', 'kode_telepon' => '692' ],
            [ 'nama' => 'Martinique', 'kode_telepon' => '596' ],
            [ 'nama' => 'Mauritania', 'kode_telepon' => '222' ],
            [ 'nama' => 'Mauritius', 'kode_telepon' => '230' ],
            [ 'nama' => 'Mayotte', 'kode_telepon' => '262' ],
            [ 'nama' => 'Mexico', 'kode_telepon' => '52' ],
            [ 'nama' => 'Micronesia', 'kode_telepon' => '691' ],
            [ 'nama' => 'Moldova', 'kode_telepon' => '373' ],
            [ 'nama' => 'Monaco', 'kode_telepon' => '377' ],
            [ 'nama' => 'Mongolia', 'kode_telepon' => '976' ],
            [ 'nama' => 'Montenegro', 'kode_telepon' => '382' ],
            [ 'nama' => 'Montserrat', 'kode_telepon' => '1664' ],
            [ 'nama' => 'Morocco', 'kode_telepon' => '212' ],
            [ 'nama' => 'Mozambique', 'kode_telepon' => '258' ],
            [ 'nama' => 'Myanmar', 'kode_telepon' => '95' ],
            [ 'nama' => 'Namibia', 'kode_telepon' => '264' ],
            [ 'nama' => 'Nauru', 'kode_telepon' => '674' ],
            [ 'nama' => 'Nepal', 'kode_telepon' => '977' ],
            [ 'nama' => 'Netherlands', 'kode_telepon' => '31' ],
            [ 'nama' => 'New Caledonia', 'kode_telepon' => '687' ],
            [ 'nama' => 'New Zealand', 'kode_telepon' => '64' ],
            [ 'nama' => 'Nicaragua', 'kode_telepon' => '505' ],
            [ 'nama' => 'Niger', 'kode_telepon' => '227' ],
            [ 'nama' => 'Nigeria', 'kode_telepon' => '234' ],
            [ 'nama' => 'Niue', 'kode_telepon' => '683' ],
            [ 'nama' => 'Norfolk Island', 'kode_telepon' => '672' ],
            [ 'nama' => 'North Korea', 'kode_telepon' => '850' ],
            [ 'nama' => 'Northern Mariana Islands', 'kode_telepon' => '1670' ],
            [ 'nama' => 'Norway', 'kode_telepon' => '47' ],
            [ 'nama' => 'Oman', 'kode_telepon' => '968' ],
            [ 'nama' => 'Pakistan', 'kode_telepon' => '92' ],
            [ 'nama' => 'Palau', 'kode_telepon' => '680' ],
            [ 'nama' => 'Palestine', 'kode_telepon' => '970' ],
            [ 'nama' => 'Panama', 'kode_telepon' => '507' ],
            [ 'nama' => 'Papua New Guinea', 'kode_telepon' => '675' ],
            [ 'nama' => 'Paraguay', 'kode_telepon' => '595' ],
            [ 'nama' => 'Peru', 'kode_telepon' => '51' ],
            [ 'nama' => 'Philippines', 'kode_telepon' => '63' ],
            [ 'nama' => 'Pitcairn Islands', 'kode_telepon' => '870' ],
            [ 'nama' => 'Poland', 'kode_telepon' => '48' ],
            [ 'nama' => 'Portugal', 'kode_telepon' => '351' ],
            [ 'nama' => 'Puerto Rico', 'kode_telepon' => '1' ],
            [ 'nama' => 'Qatar', 'kode_telepon' => '974' ],
            [ 'nama' => 'Romania', 'kode_telepon' => '40' ],
            [ 'nama' => 'Russia', 'kode_telepon' => '7' ],
            [ 'nama' => 'Rwanda', 'kode_telepon' => '250' ],
            [ 'nama' => 'Reunion', 'kode_telepon' => '262' ],
            [ 'nama' => 'Samoa', 'kode_telepon' => '685' ],
            [ 'nama' => 'San Marino', 'kode_telepon' => '378' ],
            [ 'nama' => 'Saudi Arabia', 'kode_telepon' => '966' ],
            [ 'nama' => 'Senegal', 'kode_telepon' => '221' ],
            [ 'nama' => 'Serbia', 'kode_telepon' => '381' ],
            [ 'nama' => 'Seychelles', 'kode_telepon' => '248' ],
            [ 'nama' => 'Sierra Leone', 'kode_telepon' => '232' ],
            [ 'nama' => 'Singapore', 'kode_telepon' => '65' ],
            [ 'nama' => 'Sint Maarten', 'kode_telepon' => '1721' ],
            [ 'nama' => 'Slovakia', 'kode_telepon' => '421' ],
            [ 'nama' => 'Slovenia', 'kode_telepon' => '386' ],
            [ 'nama' => 'Solomon Islands', 'kode_telepon' => '677' ],
            [ 'nama' => 'Somalia', 'kode_telepon' => '252' ],
            [ 'nama' => 'South Africa', 'kode_telepon' => '27' ],
            [ 'nama' => 'South Georgia & South Sandwich Islands', 'kode_telepon' => '500' ],
            [ 'nama' => 'South Korea', 'kode_telepon' => '82' ],
            [ 'nama' => 'South Sudan', 'kode_telepon' => '211' ],
            [ 'nama' => 'Spain', 'kode_telepon' => '34' ],
            [ 'nama' => 'Sri Lanka', 'kode_telepon' => '94' ],
            [ 'nama' => 'St. Barthalemy', 'kode_telepon' => '590' ],
            [ 'nama' => 'St. Helena', 'kode_telepon' => '290' ],
            [ 'nama' => 'St. Kitts & Nevis', 'kode_telepon' => '1869' ],
            [ 'nama' => 'St. Lucia', 'kode_telepon' => '1758' ],
            [ 'nama' => 'St. Martin', 'kode_telepon' => '590' ],
            [ 'nama' => 'St. Pierre & Miquelon', 'kode_telepon' => '508' ],
            [ 'nama' => 'St. Vincent & Grenadines', 'kode_telepon' => '1784' ],
            [ 'nama' => 'Sudan', 'kode_telepon' => '249' ],
            [ 'nama' => 'Suriname', 'kode_telepon' => '597' ],
            [ 'nama' => 'Svalbard & Jan Mayen', 'kode_telepon' => '47' ],
            [ 'nama' => 'Swaziland', 'kode_telepon' => '268' ],
            [ 'nama' => 'Sweden', 'kode_telepon' => '46' ],
            [ 'nama' => 'Switzerland', 'kode_telepon' => '41' ],
            [ 'nama' => 'Syria', 'kode_telepon' => '963' ],
            [ 'nama' => 'Sao Tome and Principe', 'kode_telepon' => '239' ],
            [ 'nama' => 'Taiwan', 'kode_telepon' => '886' ],
            [ 'nama' => 'Tajikistan', 'kode_telepon' => '992' ],
            [ 'nama' => 'Tanzania', 'kode_telepon' => '255' ],
            [ 'nama' => 'Thailand', 'kode_telepon' => '66' ],
            [ 'nama' => 'Timor-Leste', 'kode_telepon' => '670' ],
            [ 'nama' => 'Togo', 'kode_telepon' => '228' ],
            [ 'nama' => 'Tokelau', 'kode_telepon' => '690' ],
            [ 'nama' => 'Tonga', 'kode_telepon' => '676' ],
            [ 'nama' => 'Trinidad & Tobago', 'kode_telepon' => '1868' ],
            [ 'nama' => 'Tunisia', 'kode_telepon' => '216' ],
            [ 'nama' => 'Turkey', 'kode_telepon' => '90' ],
            [ 'nama' => 'Turkmenistan', 'kode_telepon' => '993' ],
            [ 'nama' => 'Turks & Caicos Islands', 'kode_telepon' => '1649' ],
            [ 'nama' => 'Tuvalu', 'kode_telepon' => '688' ],
            [ 'nama' => 'U.S. Virgin Islands', 'kode_telepon' => '1340' ],
            [ 'nama' => 'UK', 'kode_telepon' => '44' ],
            [ 'nama' => 'US', 'kode_telepon' => '1' ],
            [ 'nama' => 'Uganda', 'kode_telepon' => '256' ],
            [ 'nama' => 'Ukraine', 'kode_telepon' => '380' ],
            [ 'nama' => 'United Arab Emirates', 'kode_telepon' => '971' ],
            [ 'nama' => 'Uruguay', 'kode_telepon' => '598' ],
            [ 'nama' => 'Uzbekistan', 'kode_telepon' => '998' ],
            [ 'nama' => 'Vanuatu', 'kode_telepon' => '678' ],
            [ 'nama' => 'Vatican City', 'kode_telepon' => '3906' ],
            [ 'nama' => 'Venezuela', 'kode_telepon' => '58' ],
            [ 'nama' => 'Vietnam', 'kode_telepon' => '84' ],
            [ 'nama' => 'Wallis & Futuna', 'kode_telepon' => '681' ],
            [ 'nama' => 'Western Sahara', 'kode_telepon' => '212' ],
            [ 'nama' => 'Yemen', 'kode_telepon' => '967' ],
            [ 'nama' => 'Zambia', 'kode_telepon' => '260' ],
            [ 'nama' => 'Zimbabwe', 'kode_telepon' => '263' ],
        ]);
    }
}
